let ENDPOINT_BASE=`${php_var.rest_url+php_var.post_type}/?per_page=10&orderby=start_timestamp`;class List{init(){this._container=document.querySelector('.events');if(!this._container){return;}
this._category=this._container.getAttribute('data-category');this._category&&(ENDPOINT_BASE+=`&category=${this._category}`);this._totalPage={upcoming:0,past:0};this._currentPage={upcoming:1,past:1};this._upcomingEvents=[];this._pastEvents=[];this._type='upcoming';this._isLoading=false;const buttonContainer=document.createElement('div');buttonContainer.classList.add('upcoming_past_buttons');const upcomingButton=document.createElement('div');upcomingButton.setAttribute('id','upcoming_events');upcomingButton.classList.add('active');upcomingButton.innerHTML=php_var.upcoming_events_str;const pastButton=document.createElement('div');pastButton.setAttribute('id','past_events');pastButton.innerHTML=php_var.past_events_str;buttonContainer.appendChild(upcomingButton);buttonContainer.appendChild(pastButton);upcomingButton.addEventListener('click',()=>{this._type='upcoming';this._upcomingEventsContainer.classList.remove('events_hide');this._pastEventsContainer.classList.add('events_hide');upcomingButton.classList.add('active');pastButton.classList.remove('active');!this._upcomingEvents.length&&this._fetchData(`${ENDPOINT_BASE}&type=${this._type}&order=asc`);},false);pastButton.addEventListener('click',()=>{this._type='past';this._upcomingEventsContainer.classList.add('events_hide');this._pastEventsContainer.classList.remove('events_hide');upcomingButton.classList.remove('active');pastButton.classList.add('active');!this._pastEvents.length&&this._fetchData(`${ENDPOINT_BASE}&type=${this._type}&order=desc`);},false);this._container.appendChild(buttonContainer);this._upcomingEventsContainer=document.createElement('div');this._upcomingEventsContainer.setAttribute('id','events_upcomingevents');this._pastEventsContainer=document.createElement('div');this._pastEventsContainer.setAttribute('id','events_pastevents');this._pastEventsContainer.classList.add('events_hide');this._container.appendChild(this._upcomingEventsContainer);this._container.appendChild(this._pastEventsContainer);window.addEventListener('scroll',()=>{if(window.innerHeight+window.scrollY>document.body.offsetHeight-200){if(!this._isLoading&&this._currentPage[this._type]<=this._totalPage[this._type]){const order=this._type==='upcoming'?'asc':'desc';const endpoint=`${ENDPOINT_BASE}&type=${this._type}&page=${this._currentPage[this._type]}&order=${order}`;this._fetchData(endpoint,this._fetchCallback);}}});this._fetchData(`${ENDPOINT_BASE}&type=${this._type}&order=asc`);}
_fetchData(API){this._isLoading=true;this._renderLoadingElement(this._type==='past'?this._pastEventsContainer:this._upcomingEventsContainer);fetch(API).then((res)=>{!this._totalPage[this._type]&&(this._totalPage[this._type]=res.headers.get('x-wp-totalpages'));return res.json();}).then((result)=>{this._fetchCallback(result);this._isLoading=false;},(error)=>{console.error(error);this._isLoading=false;})}
_fetchCallback(data){this._removeLoadingElement();if(this._type==='upcoming'){data.forEach(post=>{this._upcomingEvents.push(post);this._createEventElement(post,this._upcomingEventsContainer);});}else{data.forEach(post=>{this._pastEvents.push(post);this._createEventElement(post,this._pastEventsContainer);});}
this._currentPage[this._type]+=1;if(this._currentPage[this._type]>this._totalPage[this._type]){if(this._type==='upcoming'&&this._upcomingEvents.length===0){this._upcomingEventsContainer.classList.add('aevent','nonefound','events_upcomingevents');this._upcomingEventsContainer.innerHTML=`<h3>${php_var.no_upcoming_events_str}</h3>`;}
if(this._type==='past'&&this._pastEvents.length===0){this._pastEventsContainer.classList.add('aevent','nonefound','events_upcomingevents');this._pastEventsContainer.innerHTML=`<h3>${php_var.no_upcoming_events_str}</h3>`;}}}
_renderLoadingElement(parent){if(!this._loadingElement){this._loadingElement=document.createElement('div');this._loadingElement.classList.add('lds-facebook');this._loadingElement.innerHTML='<div></div><div></div><div></div>';}
parent.appendChild(this._loadingElement);}
_removeLoadingElement(){this._loadingElement&&this._loadingElement.parentNode.removeChild(this._loadingElement);}
_createEventElement(post,parent){let start_time='';let end_time='';let start_date='';let end_date='';let timezone='';let venue='';let location='';let gsmalink='';let gsmalink_wod='';try{const metaJSON=post.meta.json;start_time=metaJSON.gsma_event_time_start;end_time=metaJSON.gsma_event_time_end;start_date=metaJSON.gsma_event_day_start;end_date=metaJSON.gsma_event_day_end;timezone=metaJSON.gsma_event_timezone;venue=metaJSON.gsma_event_venue;location=metaJSON.gsma_event_location;gsmalink=metaJSON.gsma_event_registration;gsmalink_wod=metaJSON.gsma_event_wod;}catch(error){console.error(error)}
const eventElement=document.createElement('div');eventElement.classList.add('aevent',`post-${post.id}`);eventElement.setAttribute('id',`post-${post.id}`);const eventName=document.createElement('h2');eventName.classList.add('event_name');if(gsmalink){eventName.innerHTML=`<a href=https://${gsmalink}>${post.title.rendered}</a>`;}else{eventName.innerHTML=`<a href=${post.link}>${post.title.rendered}</a>`;}
const eventInfo=document.createElement('div');eventInfo.classList.add('event_image_details_wrapper');const eventImg=document.createElement('div');eventImg.classList.add('event_image');if(gsmalink){eventImg.innerHTML=`<a href=https://${gsmalink}>
            <div class='event_image_link'>
                <img src=${post.meta.image?post.meta.image:php_var.default_image} />
            </div>
            </a>`;}else{eventImg.innerHTML=`<a href=${post.link}>
            <div class='event_image_link'>
                <img src=${post.meta.image?post.meta.image:php_var.default_image} />
            </div>
            </a>`;}
const eventDetails=document.createElement('div');eventDetails.classList.add('event_details');const startDate=document.createElement('p');startDate.classList.add('event_start_time');startDate.innerHTML=`
            <b>${php_var.start_str}: </b>
            ${this._formatDate(post.meta.start_timestamp,start_time,start_date,timezone)}
        `;eventDetails.appendChild(startDate);const endDate=document.createElement('p');endDate.classList.add('event_end_time');endDate.innerHTML=`
            <b>${php_var.end_str}: </b>
            ${this._formatDate(post.meta.end_timestamp,end_time,end_date,timezone)}
        `;eventDetails.appendChild(endDate);if(venue){const venueElement=document.createElement('p');venueElement.classList.add('event_venue');venueElement.innerHTML=`<b>${php_var.venue_str}: </b>${venue}`;eventDetails.appendChild(venueElement);}
if(location){const locationElement=document.createElement('p');locationElement.classList.add('event_location');locationElement.innerHTML=`<b>${php_var.location_str}: </b>${location}`;eventDetails.appendChild(locationElement);}
if(post.excerpt){const excerpt=document.createElement('p');excerpt.classList.add('event_excerpt');excerpt.innerHTML=post.excerpt.rendered;eventDetails.appendChild(excerpt);}
if(gsmalink){const hyperLinkTag=document.createElement("a");hyperLinkTag.setAttribute("id","registration_link");hyperLinkTag.innerHTML='Registration Link';hyperLinkTag.classList.add('event_button_href');hyperLinkTag.setAttribute("href",`https://${gsmalink}`);eventDetails.appendChild(hyperLinkTag);}
if(gsmalink_wod){const hyperLinkTag_wod=document.createElement("a");hyperLinkTag_wod.setAttribute("id","watch_demand");hyperLinkTag_wod.innerHTML='Watch On Demand';hyperLinkTag_wod.classList.add('event_button_href');hyperLinkTag_wod.setAttribute("href",`https://${gsmalink_wod}`);eventDetails.appendChild(hyperLinkTag_wod);}
eventElement.appendChild(eventName);eventElement.appendChild(eventInfo);eventInfo.appendChild(eventImg);eventInfo.appendChild(eventDetails);parent.appendChild(eventElement);}
_formatDate(timestamp,time,defaultDate,timezone=0){if(!timestamp){return '';}
const timezoneInt=parseInt(timezone,10)?parseInt(timezone,10):0;let date;if(!!defaultDate){date=new Date(Date.parse(defaultDate));}else{date=new Date(timestamp*1000);}
let formatedDate='';let formatedTime='';if(php_var.language==='cn'||php_var.language==='jp'){formatedDate=date.getFullYear()+'年'+(date.getMonth()+1)+'月'+date.getDate()+'日';}else{const month=new Intl.DateTimeFormat('en-US',{month:'long'}).format(date);const weekday=new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(date);formatedDate=weekday+' '+date.getDate()+' '+month+' '+date.getFullYear();}
if(!!time){formatedTime=time;}
return formatedDate+' '+formatedTime;}
_convertToTwoDigit(time){return(time<10?'0':'')+time;}}
const list=new List();list.init();