function _typeof(obj){"@babel/helpers - typeof";if(typeof Symbol==="function"&&typeof Symbol.iterator==="symbol"){_typeof=function _typeof(obj){return typeof obj;};}else{_typeof=function _typeof(obj){return obj&&typeof Symbol==="function"&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj;};}return _typeof(obj);}
(function($,Drupal,drupalSettings){'user strict';if(drupalSettings.chartbeat.drupal_chartbeat){var User=window.User||{};var _cbq=window._cbq=window._cbq||[];function loadChartbeat(){window._sf_endpt=new Date().getTime();var e=document.createElement('script');e.setAttribute('language','javascript');e.setAttribute('type','text/javascript');e.setAttribute('src','//static.chartbeat.com/js/chartbeat.js');document.body.appendChild(e);}
if(User&&typeof User.getUserID=='function'&&User.getUserID()){$(window).on('user-object-created.chartbeat',function(){$(window).off('user-object-created.chartbeat');var tier='lgdin';if(User.user!==undefined&&User.user!==null&&_typeof(User.user)==='object'&&typeof User.user.Membership!=='undefined'){if(User.user.Membership.tier!='registered'){tier='paid';}}
_cbq.push(['_acct',tier]);loadChartbeat();});}else{_cbq.push(['_acct','anon']);loadChartbeat();}}})(jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_custom_js={attach:function(context,settings){var showHiddenTabletMobileAds=function(){if(themeBreakpoints.currentBreakpoint.name=='tablet'){$('.block-region-content-right .block-ad-displayrec-01-general-tablet-desktop, .block-region-content-right .block-ad-displayrec-02-general-tablet-desktop').show();}}
if(settings.noAds!=1){$(window).resize(showHiddenTabletMobileAds());if(settings.dfp_custom&&(settings.dfp_custom.adsArr||settings.autonews_homepage_ads)){var skipDesktopElesWrapper='.desktop-show, .view-this-week-issue-archive',uninitializedAdClass='initialization-disabled';var skipArticles=function(articles,total){for(var i=0;i<total;i++){if($(articles[i]).parents(skipDesktopElesWrapper).length>0){articles.splice(i,1);i--;total--;}}
return total;};if(!settings.autonews_homepage_ads){showHiddenTabletMobileAds();var articleContentType=((settings.dfp_custom.potmListingParagrahpLading===2)?'.view-grouping.potm-content .views-row':(settings.dfp_custom.potmListingParagrahpLading===1)?'.view-grouping.potm-content':'[data-content-type]:not([data-content-type=""])'),articles=$(articleContentType),variants=[],total=articles.length;total=skipArticles(articles,total);var setGeneralAds=function(){var notSetGUID=arguments[0]||false;$.each(settings.dfp_custom.adsArr,function(idx,vals){idx=+idx;if(articles[idx]||settings.dfp_custom.isAN==1){var parentEle=articles[idx]?articles[idx]:'',containers='';if(articles.prop("tagName")==='TR'){parentEle=articles[idx].closest('table');}
if(notSetGUID===true){$.each(vals,function(cidx,cval){containers+=cval;});}
else{$.each(vals,function(sidx,val){var adsClassName='crain-advertisement '+sidx;adsClassName=adsClassName.split(' ').filter(function(val){if(val){return val;}}).join('.');if((drupalSettings.dfp_custom.isAN==1||parentEle)&&$(parentEle).next('.'+adsClassName).length==0){var adDisplay=$(val);$.each(adDisplay,function(idx,item){var $item=$(item),adDisplayDFP=$item.find('[id^=google-dfp]');var guid=_.guid();$item.attr('id','ad-entity-'+guid);adDisplayDFP.attr('id','google-dfp'+guid);});adsClassName='crain-advertisement '+sidx;containers+='<div class="crain-advertisement '+sidx+'" data-sub-idx="'+sidx+'" data-parent-idx="'+idx+'">'+$('<div>').append(adDisplay).html()+'</div>';variants.push(adDisplay);}});}
if(containers!=''&&$(containers).hasClass('block-photo-flipper')&&$('.block-photo-flipper').length>0){if(!$('.block-photo-flipper').next('div').hasClass('crain-advertisement')){$(containers).insertAfter('.block-photo-flipper');containers='';}
else{containers='';}}
if(containers!=''&&$(containers).hasClass('view-crain-middle-v1')&&$('.view-crain-middle-v1').length>0){var middleV1ArticleClass='.view-crain-middle-v1 .views-row',middleV1Articles=$(middleV1ArticleClass),middleV1ArticlesCount=middleV1Articles.length||0;if(middleV1ArticlesCount>idx){$(containers).insertAfter($(middleV1Articles[idx]));containers='';}}
containers!=''?(parentEle?$(containers).insertAfter(parentEle):($('article .region-featured-left').length>0?$(containers).appendTo($('article .region-featured-left')[0]):$(containers).appendTo($('article .region-featured-right')[0]))):'';if(containers!=''){containers=$(containers);if(containers.hasClass('native_sponsor')){containers.find('[data-dfp-sizes]').css({'width':containers.parent().css('width')});}}}});};}
if(settings.dfp_custom.section_pages){$($(document),context).once('addTabletAds').each(setGeneralAds);if(settings.dfp_custom.isAN!=1){var recNumber=0,container='',startKey=0;$.each(settings.dfp_custom.adsArr,function(key,vals){$.each(vals,function(idx,val){var html='<div class="crain-advertisement '+idx+'">'+val+'</div>';if(idx=='mobile'){container+=html;startKey=+key;return;}});});var prefixStart=startKey;if(settings.dfp_custom.home_page==1){prefixStart+=2;}
var total_page_item='',pager_number='',pager='',totalAdsCount=settings.dfp_custom.total?settings.dfp_custom.total:20;if($('ul.pager__items li').hasClass('is-active')){pager=$('ul.pager__items li.is-active a');if(pager.length>0){var pager_link=pager.attr('href');pager_number=parseInt(pager_link[pager_link.length-1]);total_page_item=15;if(settings.site_code=='aac'){if((typeof settings.dfp_custom.adsSlots=='object')&&settings.dfp_custom.adsSlots.length>0){setGeneralAds(true);window.googletag.pubads().refresh(settings.dfp_custom.adsSlots);}
else{settings.dfp_custom.adsSlots=[];window.addEventListener('adEntity:initialized',function(evt){var slot=evt.detail.container.ad_tag.data('slot'),crainWrapper=$(evt.detail.container.el).parents('.crain-advertisement');if(slot&&(crainWrapper.length>0)){crainWrapper=$(crainWrapper[0]);settings.dfp_custom.adsSlots.push(evt.detail.container.ad_tag.data('slot'));settings.dfp_custom.adsArr[crainWrapper.attr('data-parent-idex')]={};settings.dfp_custom.adsArr[crainWrapper.attr('data-parent-idx')][crainWrapper.attr('data-sub-idx')]=crainWrapper[0].outerHTML;}});}}}}
if(settings.site_code!='aac'){$.each(articles,function(idx,article){if(pager_number!=0&&total_page_item!='undefined'&&total_page_item!=''){if(((idx+(total_page_item*pager_number)+pager_number)%6)===0&&$(article).next('.crain-advertisement.mobile').length==0){var recNumber=((idx+(total_page_item*pager_number)+pager_number)/6+prefixStart);if(recNumber<=totalAdsCount){getAdUnit(recNumber,article);}}}
else{if(((idx===startKey)||((idx+1)%6)===0)&&$(article).next('.crain-advertisement.mobile').length==0){var recNumber=(idx===startKey)?prefixStart:((idx+1)/6+prefixStart);if(recNumber<=totalAdsCount){getAdUnit(recNumber,article);}}}});}}}
else if(settings.autonews_homepage_ads){var ads=settings.autonews_homepage_ads;if(ads&&typeof ads=='object'){var articleContentType='.autonews .top [data-content-type]:not([data-content-type=""])',middleV1ArticleClass='.autonews .left .view-crain-middle-v1 .views-row',topArticles=$(articleContentType),middleV1Articles=$(middleV1ArticleClass),topArticleCount=topArticles.length||0,middleV1ArticlesCount=middleV1Articles.length||0,totalArticles=topArticleCount+middleV1ArticlesCount,desktopTabletAds=ads.desktop_tablet,mobileAds=ads.mobile,variants=[];var insertAutoNewsHomeAds=function(ads){$.each(ads,function(key,ad){var middle=ad.middle||0,pos=ad.pos||0,render=ad.render;$render=$(render);if(middle==1&&middleV1ArticlesCount>pos){$render.insertAfter($(middleV1Articles[pos]));}
else{if(pos<topArticleCount){$render.insertAfter($(topArticles[pos]));}
else{$render.insertAfter($(middleV1Articles[pos-topArticleCount]));}}});};if(totalArticles>0){insertAutoNewsHomeAds(desktopTabletAds);topArticleCount=skipArticles(topArticles,topArticleCount);middleV1ArticlesCount=skipArticles(middleV1Articles,middleV1ArticlesCount);totalArticles=topArticleCount+middleV1ArticlesCount;insertAutoNewsHomeAds(mobileAds);}}}
else{setGeneralAds();}
function getAdUnit(recNumber,article){var customTargeting={},adDisplay=$(container).find('[data-ad-entity]'),adDisplayDFP=adDisplay.find('[id^=google-dfp]'),guid=_.guid();if(adDisplay.length>0&&adDisplayDFP.length>0){adDisplay.attr('id','ad-entity-'+guid);adDisplayDFP.attr('id','google-dfp'+guid);adDisplay.html(adDisplayDFP[0].outerHTML);var targetings=JSON.parse($(adDisplay).attr('data-ad-entity-targeting'))||{};if(targetings.pos){var pos=targetings.pos.split('_');if(recNumber<=9){pos[1]='0'+recNumber;}
else{pos[1]=recNumber;}
customTargeting.pos=pos.join('_');}
_.extend(targetings,customTargeting);adDisplay.attr('data-ad-entity-targeting',JSON.stringify(targetings));variants.push(adDisplay);$($(container).html(adDisplay[0].outerHTML)[0].outerHTML).insertAfter(article);}}
var resetAdsPositionTopBottomRight=function(){var prefixAn=settings.autonews_homepage_ads?'.an-right':'',rightBlockAds=$('.block-region-content-right'+prefixAn+' [data-block-plugin-id^="ad_display"]'),rightBlockAdsLength=rightBlockAds.length||0,rightComponentBlock=$('.block-region-content-right'+prefixAn+' [data-block-plugin-id]:not([data-block-plugin-id^="ad_display"])'),rightComponentBlockLength=rightComponentBlock.length||0,autonewSectionFrontPages=$('.block-region-content-right[class*="crain-autonews-"]'),leftAdsCount=0,insertAfter=arguments[0]||false;var sponsorBlockWrapper=false;var isAwardProgramPage=false;var citybookArticle=false;if(drupalSettings.site_code=='can'||drupalSettings.site_code=='cane'){isAwardProgramPage=$("body").hasClass("page-node-type-award-program");if(isAwardProgramPage==true){sponsorBlockWrapper=$("div").hasClass("sponsored-block-wrapper");}}
if(($.inArray(drupalSettings.site_code,['ccl','cdb','cny'])>-1)&&($('.node--type-article.node--view-mode-full').length>=1)){citybookArticle=true;}
if(rightBlockAdsLength>0){if(rightComponentBlockLength>0&&sponsorBlockWrapper!=true){var separate=Math.round(rightComponentBlockLength/rightBlockAdsLength);if(settings.autonews_homepage_ads){rightBlockAds.each(function(idx){if(rightBlockAdsLength==1){$(this).insertAfter($(rightComponentBlock[Math.ceil(rightComponentBlockLength/2)-1]));}
else{var pos=separate*(idx+1)-1;if(pos<rightComponentBlockLength){insertAfter===true?$(this).insertAfter($(rightComponentBlock[pos])):$(this).insertBefore($(rightComponentBlock[pos]));}
else{$(this).insertAfter($(rightComponentBlock[rightComponentBlockLength-1]));}}});}
else if(autonewSectionFrontPages.length>0){leftAdsCount=rightBlockAdsLength-rightComponentBlockLength;switch(rightComponentBlockLength){case 1:$.each(rightComponentBlock,function(key,ads){if(key<rightBlockAdsLength-1){$(rightBlockAds[key]).insertBefore(rightComponentBlock);}});break;case 2:case 3:$.each(rightComponentBlock,function(key,ele){if(rightBlockAdsLength>key){$(rightBlockAds[key]).insertBefore($(ele));}});break;case 4:leftAdsCount=rightBlockAdsLength;$.each(rightComponentBlock,function(key,ele){if(rightBlockAdsLength>key&&key%2==0){$(rightBlockAds[key]).insertBefore($(ele));leftAdsCount--;}});break;case 5:leftAdsCount=rightBlockAdsLength;$.each(rightComponentBlock,function(key,ele){if(rightBlockAdsLength>key&&key<2){$(rightBlockAds[key]).insertAfter($(ele));leftAdsCount--;}});break;}
while(leftAdsCount>0){$(rightBlockAds[rightBlockAdsLength-leftAdsCount]).insertAfter($(rightComponentBlock[rightComponentBlockLength-1]));leftAdsCount--;}}
else{if(($('.node--view-mode-cmh_full, .node--view-mode-cmh_full_thub, .node--type-article.node--view-mode-ccb_full, .node--type-article.node--view-mode-crain_polymer').length<1)&&citybookArticle==false){rightBlockAds.each(function(idx){if((rightComponentBlockLength==1)&&(idx<=1)){(idx===0)?$(this).insertBefore($(rightComponentBlock[0])):$(this).appendTo($(rightComponentBlock[0]));}
else if((rightComponentBlockLength>=2)&&(rightBlockAdsLength>=2)&&(idx<=1)){(idx===0)?$(this).insertBefore($(rightComponentBlock[0])):$(this).appendTo($(rightComponentBlock[1]));}
else{if(settings.isAacArticle!=1){$(this).appendTo($(rightComponentBlock[rightComponentBlockLength-1]));}}});}}}
else{if(settings.isAacArticle!=1&&settings.isCpeArticle!=1&&settings.isTermPage!=1&&settings.isSearchPage!=1){$.each(rightBlockAds,function(idx,ad){$($('.block-region-content-right')[0]).append($(ad));});}}}
var topBlockAds=$('.block-region-content-top > [data-block-plugin-id^="ad_display"][data-block-plugin-id*="lb_"]');if(topBlockAds.length>0){$('.block-region-content-top').prepend(topBlockAds);}
if(settings.isSearchPage==1&&($(window).width()<768)){$('.block-region-content-bottom').append($('.sponsored-content-block'));}
var bottomBlockAds=$('.block-region-content-bottom > [data-block-plugin-id^="ad_display"][data-block-plugin-id*="lb_"]');var nodeDetail=$('.node--type-article.node--view-mode-full');if(bottomBlockAds.length>0&&$('.node--type-work.node--view-mode-full').length<1&&(settings.site_code=='ccl'&&nodeDetail.length<1)){$('.block-region-content-bottom').prepend(bottomBlockAds);}};if(settings.site_code!='cpi'){$($(document),context).once('resetAdsPositionTopBottomRight').each(function(){resetAdsPositionTopBottomRight(false);});}
if(settings.dfp_custom.dataDfpUnitSuffix){var adElements=$('[data-dfp-unit]'),uninitializedAd=$('.'+uninitializedAdClass),hashValues=window.location.hash||'',adUnit=settings.dfp_ad_unit_override||'',testSection='',testTargeting='',spcTargeting='',unitTargeting='',adunitOveridePath='';hashValues=hashValues.split('&'),filterEmptyFunc=function(val){if(val){return true;}
else{return false;}};$.each(hashValues,function(idx,value){var values=value.split('=');if(['cci_test','#cci_test'].indexOf(values[0])>=0){testSection=testSection||'test';testTargeting=values[1]||testTargeting;unitTargeting='test';}
if(['aao_spc','#aao_spc'].indexOf(values[0])>=0){testTargeting=values[1]||testTargeting;unitTargeting='aao_spc';}
if(['adunit_path','#adunit_path'].indexOf(values[0])>=0){adunitOveridePath=values[1]||adunitOveridePath;}});if(adunitOveridePath){var adPaths=settings.dfp_custom.dataDfpUnitSuffix.split('/');settings.dfp_custom.dataDfpUnitSuffixModified=adPaths[adPaths.length-1];}
else{settings.dfp_custom.dataDfpUnitSuffixModified=settings.dfp_custom.dataDfpUnitSuffix;}
$.each(adElements,function(idx,adElement){adUnit=adUnit!=''?adUnit:$(adElement).attr('data-dfp-unit').split('/')[0];if(testSection){var adUnitPath=_.filter([adUnit,testSection],filterEmptyFunc);}
else{var adUnitPath=_.filter([adUnit,adunitOveridePath,settings.dfp_custom.dataDfpUnitSuffixModified],filterEmptyFunc);}
$(adElement).attr('data-dfp-unit',adUnitPath.join('/'));});if(settings.dfp_custom.targeting||testTargeting){var adElementsTargeting=$('[data-ad-entity-targeting]'),customTargeting=settings.dfp_custom.targeting?JSON.parse(settings.dfp_custom.targeting):{},targeting={};$.each(customTargeting,function(idx,target){delete customTargeting[idx];idx=idx.replace('adunit',adUnit);customTargeting[idx]=target;});$.each(adElementsTargeting,function(idx,adElement){targeting=JSON.parse($(adElement).attr('data-ad-entity-targeting'))||{};_.extend(targeting,customTargeting);if(testTargeting){targeting[unitTargeting]=testTargeting;}
$(adElement).attr('data-ad-entity-targeting',JSON.stringify(targeting));});}}
var iterativeGetWidth=function(ele){var width=ele.css('width');if(parseInt(width)>0){return width;}
return iterativeGetWidth(ele.parent());}
var resizeNativeAds=function(){var nativeAds=$('[data-ad-entity-targeting*=NTV_] [data-dfp-sizes], [data-ad-entity-targeting*=ntv_] [data-dfp-sizes]');var filterNativeAds=nativeAds.filter(function(){return JSON.parse(this.parentElement.getAttribute('data-ad-entity-targeting')).pos.match(/ntv_(\d)+/i);});filterNativeAds.each(function(idx,element){if($(element).parents('.native_sponsor').length>0){var width=iterativeGetWidth($(element).parents('.native_sponsor').parent());$(element).css({'width':width});}
else{var width=iterativeGetWidth($(element).parent());$(element).css({'width':width});}});};$(window).resize(resizeNativeAds);$(window).on('load',resizeNativeAds);}}}};})(window.adEntity,jQuery,Drupal,drupalSettings);;var jamData=[],globalTargeting={};(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_desktop_custom={attach:function(context,settings){$(window).on("load",function(){if($(".view-content.view-display-id-page_1 .view-filters select#edit-type").length>0){$(".view-content.view-display-id-page_1 .view-filters select#edit-type").chosen({width:"210px"});}
$(".view-content.view-display-id-page_1 .view-filters select#edit-type").trigger("chosen:updated");$('#edit_type_chosen ul li input.chosen-search-input').val('Choose some options');$('#edit-moderation-state').children('optgroup').children().unwrap();});$($(document),context).once('addMobileAds').each(function(){if(settings.noAds!=1&&(settings.dfp_custom_desktop&&settings.dfp_custom_desktop.adsArr)&&(settings.path.isFront)){var articleContentType='[data-region-name]:not([data-region-name=""])',skipDesktopElesWrapper='.desktop-show',uninitializedAdClass='initialization-disabled',articles=$(articleContentType),variants=[],total=articles.length;var count=0;for(var i=0;i<total;i++){if($(articles[i]).parents(skipDesktopElesWrapper).length>0){articles.splice(i,1);i--;total--;}}
$.each(settings.dfp_custom_desktop.adsArr,function(idx,vals){idx=+idx;if(articles[idx]){var parentEle=$('.block-block-content'),containers='';var numItems=$('.block-region-content-right .block-block-content').length;$.each(vals,function(idx,val){if(val.length>0){containers+='<div class="crain-advertisement '+idx+'">'+val+'</div>';variants.push($(val));}});if(numItems>0){if(count==0){$(".block-region-content-right > div:nth-child(1)").before(containers);}
else{$(".block-region-content-right > div:nth-child(3)").after(containers);}
if(numItems==1){$(".block-region-content-right > div:nth-child(2)").after(containers);}}
else{var parentEle=$('.block-region-content-right');parentEle?$(containers).insertAfter(parentEle):'';}}
count=count+1;});if(settings.dfp_custom_desktop.dataDfpUnitSuffix){var adElements=$('[data-dfp-unit]'),uninitializedAd=$('.'+uninitializedAdClass),hashValues=window.location.hash||'',adUnit=settings.dfp_ad_unit_override||'',testSection='',testTargeting='',spcTargeting='',unitTargeting='',adunitOveridePath='';hashValues=hashValues.split('&'),filterEmptyFunc=function(val){if(val){return true;}
else{return false;}};$.each(hashValues,function(idx,value){var values=value.split('=');if(['cci_test','#cci_test'].indexOf(values[0])>=0){testSection=testSection||'test';testTargeting=values[1]||testTargeting;unitTargeting='test';}
if(['aao_spc','#aao_spc'].indexOf(values[0])>=0){testTargeting=values[1]||testTargeting;unitTargeting='aao_spc';}
if(['adunit_path','#adunit_path'].indexOf(values[0])>=0){adunitOveridePath=values[1]||adunitOveridePath;}});if(adunitOveridePath){var adPaths=settings.dfp_custom_desktop.dataDfpUnitSuffix.split('/');settings.dfp_custom_desktop.dataDfpUnitSuffix=adPaths[adPaths.length-1];}
$.each(adElements,function(idx,adElement){adUnit=adUnit!=''?adUnit:$(adElement).attr('data-dfp-unit').split('/')[0];if(testSection){var adUnitPath=_.filter([adUnit,testSection],filterEmptyFunc);}
else{var adUnitPath=_.filter([adUnit,adunitOveridePath,settings.dfp_custom_desktop.dataDfpUnitSuffix],filterEmptyFunc);}
$(adElement).attr('data-dfp-unit',adUnitPath.join('/'));if(testTargeting){var adElementsTargeting=$(adElement).parent('[data-ad-entity-targeting]'),targeting=JSON.parse($(adElementsTargeting).attr('data-ad-entity-targeting'))||{};targeting[unitTargeting]=testTargeting;$(adElementsTargeting).attr('data-ad-entity-targeting',JSON.stringify(targeting));}});}}});}};})(window.adEntity,jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_sponsored_custom={attach:function(context,settings){$($(document),context).once('addSponsoredDFPAds').each(function(){if(settings.noAds!=1){var resetSponsoredAds=$('.sponsored-dfp-ads-reset');$.each(resetSponsoredAds,function(idx,elem){var dfpTargetPos=$(elem).data('reset-target-pos'),adDisplay=$(elem).find('[data-ad-entity-targeting]');if(adDisplay.length>0){var targetings=JSON.parse($(adDisplay).attr('data-ad-entity-targeting'))||{};_.extend(targetings,{"pos":dfpTargetPos});adDisplay.attr('data-ad-entity-targeting',JSON.stringify(targetings));}});}});}};})(window.adEntity,jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_sponsored_taxonomy_custom={attach:function(context,settings){if(settings.noAds!=1&&settings.sponsored_taxonomy_dfp_ads&&(settings.sponsored_taxonomy_dfp_ads.block||settings.sponsored_taxonomy_dfp_ads.nativeBlock)){var sponsoredTaxonomyDFPBlock=settings.sponsored_taxonomy_dfp_ads.block,nativeSponsoredTaxonomyDFPBlock=settings.sponsored_taxonomy_dfp_ads.nativeBlock,dfpUnitId=(settings.dfp_custom&&settings.dfp_custom.dataDfpUnitSuffix)?settings.dfp_custom.dataDfpUnitSuffix:(settings.dfp_article_custom&&settings.dfp_article_custom.dataDfpUnitSuffix?settings.dfp_article_custom.dataDfpUnitSuffix:''),fixedSponsoredPos='data-ad-entity-fixed-pos',fixedSponsorAds=$('['+fixedSponsoredPos+']:not(['+fixedSponsoredPos+'=""])'),fixedPos=[];if(fixedSponsorAds.length>0){fixedSponsorAds.each(function(idx,value){fixedPos.push($(value).attr(fixedSponsoredPos));});}
_.mixin({guid:function(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16);});}});var resetSponsoredAdTag='[data-dfp-sponsored-category]:not([data-dfp-sponsored-category=""]):not([data-dfp-native-sponsored])',resetSponsoredAds=$(resetSponsoredAdTag),resetNativeSponsoredAdTag='[data-dfp-sponsored-category][data-dfp-native-sponsored]:not([data-dfp-sponsored-category=""])',resetNativeSponsoredAds=$(resetNativeSponsoredAdTag),variants=[],hashValues=window.location.hash||'',adUnit=settings.dfp_ad_unit_override||'',testSection='',testTargeting='',spcTargeting='',unitTargeting='',adunitOveridePath='',hashValues=hashValues.split('&'),filterEmptyFunc=function(val){if(val){return true;}
else{return false;}};$.each(hashValues,function(idx,value){var values=value.split('=');if(['cci_test','#cci_test'].indexOf(values[0])>=0){testSection=testSection||'test';testTargeting=values[1]||testTargeting;unitTargeting='test';}
if(['aao_spc','#aao_spc'].indexOf(values[0])>=0){testTargeting=values[1]||testTargeting;unitTargeting='aao_spc';}
if(['adunit_path','#adunit_path'].indexOf(values[0])>=0){adunitOveridePath=values[1]||adunitOveridePath;}});if(adunitOveridePath){var adPaths=dfpUnitId.split('/');dfpUnitId=adPaths[adPaths.length-1];}
var max=20,existedLogoAds=$('[data-dfp-sponsored-category]:not([data-dfp-native-sponsored]) [data-ad-entity-targeting]').length,existedNativeLogoAds=$('[data-dfp-sponsored-category][data-dfp-native-sponsored] [data-ad-entity-targeting]').length,leftLogoAds=max-existedLogoAds,leftNativeLogoAds=max-existedNativeLogoAds;var changeSponsorAdsPos=function(existedLogoAds,pos,max){if(existedLogoAds<=8){pos[1]='0'+(existedLogoAds+1);}
else{pos[1]=(existedLogoAds+1);}
++existedLogoAds;leftLogoAds=max-existedLogoAds;return[existedLogoAds,leftLogoAds];};var replaceSponsoredLogoAds=function(leftLogoAds,resetSponsoredAds,sponsoredTaxonomyDFPBlock,adUnit,existedLogoAds,max,variants,testSection,fixedPos,native){if(leftLogoAds>0){$.each(resetSponsoredAds,function(idx,elem){if(leftLogoAds<1){return;}
var sponsoredCategory=$(elem).data('dfp-sponsored-category'),sponsoredArticleGUID=$(elem).data('dfp-sponsored-uuid'),sponsoredTaxonomyDFPBlockClone=_.clone(sponsoredTaxonomyDFPBlock);if(!$(elem).find('[data-ad-entity-targeting]').length){$(elem).append(sponsoredTaxonomyDFPBlockClone);if(typeof native!=='undefined'&&native){$(elem).find('[data-dfp-sizes]').css({'width':$(elem).parent().css('width')});}
var adDisplay=$(elem).find('[data-ad-entity-targeting]'),adUnitTag=$($(elem).find('[data-dfp-unit]')[0]),targetings=adDisplay.length>0?JSON.parse($(adDisplay).attr('data-ad-entity-targeting')):{},adDisplayDFP=adDisplay.find('[id^=google-dfp]'),guid=_.guid(),customTargeting={};if(!adUnit&&adUnitTag.length){var adUnitTagAttr=adUnitTag.attr('data-dfp-unit');if(adUnitTagAttr){adUnit=adUnitTagAttr.split('/')[0];}}
adDisplay.attr('id','ad-entity-'+guid);adDisplayDFP.attr('id','google-dfp'+guid);targetings.pos=targetings.pos?targetings.pos:'NIV_01';targetings.category=targetings.category?targetings.category:'Sponsored 1';var pos=targetings.pos.split('_');var remain=changeSponsorAdsPos(existedLogoAds,pos,max);existedLogoAds=remain[0];leftLogoAds=remain[1];posJoin=pos.join('_');while(fixedPos.indexOf(posJoin)>-1&&leftLogoAds>0){remain=changeSponsorAdsPos(existedLogoAds,pos,max);posJoin=pos.join('_');existedLogoAds=remain[0];leftLogoAds=remain[1];}
customTargeting.pos=pos.join('_');var category=targetings.category.split(' ');category[1]=sponsoredCategory;customTargeting[adUnit+'_cat']=category.join(' ');customTargeting.guid=sponsoredArticleGUID;delete(targetings.category);if(testTargeting){targetings[unitTargeting]=testTargeting;}
_.extend(targetings,customTargeting);adDisplay.attr('data-ad-entity-targeting',JSON.stringify(targetings));variants.push($(elem).find('[data-ad-entity]')[0]);if(testSection){var adUnitPath=_.filter([adUnit,testSection],filterEmptyFunc);}
else{var adUnitPath=_.filter([adUnit,adunitOveridePath,dfpUnitId],filterEmptyFunc);}
adUnitTag.attr('data-dfp-unit',adUnitPath.join('/'));}});}};if(sponsoredTaxonomyDFPBlock){replaceSponsoredLogoAds(leftLogoAds,resetSponsoredAds,sponsoredTaxonomyDFPBlock,adUnit,existedLogoAds,max,variants,testSection,fixedPos,false);}
if(nativeSponsoredTaxonomyDFPBlock){replaceSponsoredLogoAds(leftNativeLogoAds,resetNativeSponsoredAds,nativeSponsoredTaxonomyDFPBlock,adUnit,existedNativeLogoAds,max,variants,testSection,fixedPos,true);}
var resizeNativeAdsSize=function(){$('[data-ad-entity="ad_entity_sponsored_taxonomy_logo_native"] [data-dfp-sizes]').each(function(idx,element){$(element).css({'width':$(element).parents(resetNativeSponsoredAdTag).parent().css('width')});});};$(window).resize(resizeNativeAdsSize);$(window).on('load',resizeNativeAdsSize);}}};})(window.adEntity,jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_custom_article_js={attach:function(context,settings){$($(document),context).once('addArticleParagraphAds').each(function(){if(settings.noAds!=1&&$('body.page-node-type-article .layout-container.aa-full-article-page').length<1&&settings.dfp_article_custom){var articleParagrahTag='.article-paragraph p, .node--type-whitepaper .field--name-body p, .node--type-work .field--name-body p',articleParagrahs=$(articleParagrahTag);articleParagrahs.each(function(){if($(this).html().replace(/\s|&nbsp;/g,'').length==0){$(this).addClass("empty-para");}});articleParagrahs=articleParagrahs.not(".empty-para, .article-main-image-caption p");_.mixin({guid:function(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16);});}});var skipElesWrapper='.video-js,.item--paragraph--type--factbox,.article-main-image-wrapper,.paragraph--type--photo-gallery',uninitializedAdClass='initialization-disabled',variants=[],uninitializedAd=[],total=articleParagrahs.length,inlineIdio=$('.article-recommended-inline');for(var i=0;i<total;i++){var numbers;if(inlineIdio.length>0){inlineIdio.each(function(){var n=$(this).attr('class');numbers=parseInt(n.match(/\d+/),10);if(numbers==i){articleParagrahs[i-1].className="crain-idio-inline-"+numbers;$(this).insertAfter(".crain-idio-inline-"+numbers);$(this).show();}});}
if($(articleParagrahs[i]).parents(skipElesWrapper).length>0){articleParagrahs.splice(i,1);i--;total--;}}
if(settings.dfp_article_custom.adsArr){$.each(settings.dfp_article_custom.adsArr,function(idx,vals){if(idx=='last'){idx=total-1;}
else{idx=+idx;}
if('cpi'===settings.site_code&&articleParagrahs.length===(idx+1)){return false;}
if(articleParagrahs[idx]||settings.dfp_article_custom.isAN==1){var parentEle=articleParagrahs[idx],containers='';var allowAfterone=settings.dfp_article_custom.allowAfterone||0;$.each(vals,function(k,val){if(val){if(($.inArray(settings.site_code,['ccb','ccl','cdb','cny'])>-1)&&idx==3&&k=="tablet desktop"){k="tablet";val=val.replace(',"desktop","narrow"','');}
var count=variants.length;containers+='<div class="crain-advertisement '+k+' adscount'+count+'">'+val+'</div>';variants.push($(val));}});parentEle?parentEle.classList.add('inline-ad-para'):'';containers=$(containers);parentEle?((idx==0&&allowAfterone==0)?containers.insertBefore(parentEle):(parentEle.className.indexOf('crain-idio-inline-')>-1?containers.insertAfter(parentEle.nextSibling):containers.insertAfter(parentEle))):($('article .region-featured-left').length>0?containers.appendTo($('article .region-featured-left')[0]):containers.appendTo($('article .region-featured-right')[0]));if(containers.hasClass('native_sponsor')){if(containers.hasClass('half')){var articleFieldItem='.article-paragraph > .field__item, .article-paragraph.field__item',articleFieldItems=$(articleFieldItem);articleFieldItems.each(function(index,value){if((index==0)&&$(this).find('.image-mugshot-left').length>0){containers.find('[data-dfp-sizes]').closest('.native_sponsor').addClass('image-mugshot-left_exist');containers.find('[data-dfp-sizes]').addClass('image-mugshot-left_exist');}});if($('.article-main-image-wrapper').hasClass('image-mugshot-left')){containers.find('[data-dfp-sizes]').closest('.native_sponsor').addClass('image-mugshot-left_exist');containers.find('[data-dfp-sizes]').addClass('image-mugshot-left_exist');}
containers.find('[data-dfp-sizes]').css({'width':parseInt(containers.parents('[data-block-plugin-id="entity_field:node:field_paragraphs"]').css('width'))/2+'px'});}
else{containers.find('[data-dfp-sizes]').css({'width':containers.parents('[data-block-plugin-id="entity_field:node:field_paragraphs"]').css('width')});}}}});if(settings.dfp_article_custom.adsArr[3]&&settings.dfp_article_custom.noIncrement!=1){var paragraphs=$('.item--paragraph--type--body .field--name-field-paragraph-body p');var startKey=2;var containers='';var tab_desktop_val=settings.dfp_article_custom.adsArr[3]["tablet desktop"]||'';var mobile_val=settings.dfp_article_custom.adsArr[3].mobile||'';var tab_val=settings.dfp_article_custom.adsArr[3]['tablet']||'';var isAN=location.host.indexOf('.autonews.com')==-1?0:1;$.each(paragraphs,function(idx,paragraph){var count=variants.length;if(idx>10){if(((idx+1)%6)==0){var recNumber=((idx+1)/6)+startKey;if(isAN===1){var recMobile=recNumber;}
else{var recMobile=((idx+1)/6);}
if(recNumber<21){if(tab_desktop_val){containers='<div class="crain-advertisement tablet desktop adscount'+count+'">'+tab_desktop_val+'</div>';getAdUnit(recNumber,paragraph,containers);}}
if(recMobile<21){if(tab_val){containers='<div class="crain-advertisement tablet adscount'+count+'">'+tab_val+'</div>';getAdUnit(recMobile,paragraph,containers);}
if(mobile_val){containers='<div class="crain-advertisement mobile adscount'+count+'">'+mobile_val+'</div>';getAdUnit(recMobile,paragraph,containers);}}}}});function getAdUnit(recNumber,paragraph,containers){var customTargeting={},adDisplay=$(containers).find('[data-ad-entity]'),adDisplayDFP=adDisplay.find('[id^=google-dfp]'),guid=_.guid();if(adDisplay.length>0&&adDisplayDFP.length>0){adDisplay.attr('id','ad-entity-'+guid);adDisplayDFP.attr('id','google-dfp'+guid);adDisplay.html(adDisplayDFP[0].outerHTML);var targetings=JSON.parse($(adDisplay).attr('data-ad-entity-targeting'))||{};if(targetings.pos){var pos=targetings.pos.split('_');if(recNumber<=9){pos[1]='0'+recNumber;}
else{pos[1]=recNumber;}
customTargeting.pos=pos.join('_');}
_.extend(targetings,customTargeting);adDisplay.attr('data-ad-entity-targeting',JSON.stringify(targetings));variants.push(adDisplay);$($(containers).html(adDisplay[0].outerHTML)[0].outerHTML).insertAfter(paragraph);}}}}
if(settings.dfp_article_custom.dataDfpUnitSuffix){var adElements=$('[data-dfp-unit]'),uninitializedAd=$('.'+uninitializedAdClass),hashValues=window.location.hash||'',adUnit=settings.dfp_ad_unit_override||'',testSection='',testTargeting='',spcTargeting='',unitTargeting='',adunitOveridePath='';hashValues=hashValues.split('&'),filterEmptyFunc=function(val){if(val){return true;}
else{return false;}};$.each(hashValues,function(idx,value){var values=value.split('=');if(['cci_test','#cci_test'].indexOf(values[0])>=0){testSection=testSection||'test';testTargeting=values[1]||testTargeting;unitTargeting='test';}
if(['aao_spc','#aao_spc'].indexOf(values[0])>=0){testTargeting=values[1]||testTargeting;unitTargeting='aao_spc';}
if(['adunit_path','#adunit_path'].indexOf(values[0])>=0){adunitOveridePath=values[1]||adunitOveridePath;}});if(adunitOveridePath){var adPaths=settings.dfp_article_custom.dataDfpUnitSuffix.split('/');settings.dfp_article_custom.dataDfpUnitSuffix=adPaths[adPaths.length-1];}
$.each(adElements,function(idx,adElement){adUnit=adUnit!=''?adUnit:$(adElement).attr('data-dfp-unit').split('/')[0];if(testSection){var adUnitPath=_.filter([adUnit,testSection],filterEmptyFunc);}
else{var adUnitPath=_.filter([adUnit,adunitOveridePath,settings.dfp_article_custom.dataDfpUnitSuffix],filterEmptyFunc);}
$(adElement).attr('data-dfp-unit',adUnitPath.join('/'));});}
if(settings.dfp_article_custom.targeting||testTargeting){var adElementsTargeting=$('[data-ad-entity-targeting]'),customTargeting=settings.dfp_article_custom.targeting?JSON.parse(settings.dfp_article_custom.targeting):{},targeting={};$.each(customTargeting,function(idx,target){delete customTargeting[idx];if(idx.indexOf('_cat')!=-1){target=target.length==1?target[0]:target;}
idx=idx.replace('adunit',adUnit);customTargeting[idx]=target;});$.each(adElementsTargeting,function(idx,adElement){targeting=JSON.parse($(adElement).attr('data-ad-entity-targeting'))||{};_.extend(targeting,customTargeting);if(testTargeting){targeting[unitTargeting]=testTargeting;}
$(adElement).attr('data-ad-entity-targeting',JSON.stringify(targeting));});}
var resetRightAdsForAn=function(){if($('.layout-2col-8x4.article').length>0){if(window.location.host.indexOf('canada.autonews.com')>-1||window.location.host.indexOf('europe.autonews.com')>-1||(drupalSettings.isCpeArticle===1&&settings.site_code!='cpn')){var rightBlockAds=$('.article-block-right [data-block-plugin-id^="ad_display"]'),rightBlockAdsLength=rightBlockAds.length||0,rightComponentBlock=$('.article-block-right  [data-block-plugin-id]:not([data-block-plugin-id^="ad_display"])'),rightComponentBlockLength=rightComponentBlock.length||0;if(rightComponentBlockLength>0&&rightBlockAdsLength>0){var separate=Math.floor(rightComponentBlockLength/rightBlockAdsLength);rightBlockAds.each(function(idx){var pos=separate+idx;if(rightComponentBlockLength>pos){$(this).insertBefore($(rightComponentBlock[pos]));}
else{$(this).appendTo($(rightComponentBlock[rightComponentBlockLength-1]).parent());}});}}}};resetRightAdsForAn();var resizeNativeAdsArticle=function(){$('.crain-advertisement.native_sponsor:not(.half) [data-dfp-sizes]').each(function(idx,element){$(element).css({'width':$(element).parents('[data-block-plugin-id="entity_field:node:field_paragraphs"], [data-block-plugin-id="entity_field:node:body"]').css('width')});});$('[data-ad-entity="an_entity_dfp_ntv_03_article"] [data-dfp-sizes]').each(function(idx,element){$(element).css({'width':$(element).parents('.block-region-content-left').css('width')});});$('.crain-advertisement.native_sponsor.half [data-dfp-sizes]').each(function(idx,element){$(element).css({'width':parseInt($(element).parents('[data-block-plugin-id="entity_field:node:field_paragraphs"], [data-block-plugin-id="entity_field:node:body"]').css('width'))/2+'px'});});};$(window).resize(resizeNativeAdsArticle);$(window).on('load',resizeNativeAdsArticle);}});function advertisementReposition(){var mugshot=$('.article-main-image-wrapper.image-mugshot-left'),advertisement=$('.adscount1');if(!mugshot.length||!advertisement.length){return false;}
var mugshot_bottom=mugshot.offset().top+mugshot.outerHeight();var advertisement_top=advertisement.offset().top;if(advertisement_top<mugshot_bottom){advertisement.addClass('overrideads');return;}
advertisement.removeClass('overrideads');}
function advertisementRepositionInlineParagraph(){$('.article-paragraph .item--paragraph--type--body').each(function(){var adsInline=$(this).find('.block').children('.field--name-field-paragraph-body').children('.desktop');if(adsInline.length){var adsOffsetLeft=adsInline.offset().left;}
var ImagesInline=$(this).prev('.mugshot-wrapper').find('.article-images-wrapper');if(ImagesInline.length){var ImageOffsetLeft=ImagesInline.offset().left;}
if(adsOffsetLeft>ImageOffsetLeft){adsInline.addClass('override-inline-ads');}});}
function adjustRightRailForAd(ad,blocks){if(ad.length>0&&ad.hasClass('not-empty')){var adOffsetTop=ad.offset().top,adOffsetHeight=ad[0].offsetHeight||0;$.each(blocks,function(k,v){var vOffsetTop=$(v).offset().top,vOffsetHeight=v.offsetHeight||0,bottom=vOffsetTop+vOffsetHeight;if(bottom>adOffsetTop){if(vOffsetTop<adOffsetTop){$('<div class="desktop-show db35dd80-7a3f-4734-a9ce-ead26fe51ea2" style="height:'+(adOffsetHeight+(adOffsetTop-vOffsetTop)+20)+'px; width:100%;"></div>').insertBefore($(v));}
else if(vOffsetTop<=(adOffsetHeight+adOffsetTop)){$('<div class="desktop-show db35dd80-7a3f-4734-a9ce-ead26fe51ea2" style="height:'+(adOffsetHeight-(vOffsetTop-adOffsetTop)+20)+'px;" width:100%;"></div>').insertBefore($(v));}}});}}
function aacShiftRightRailForLB_03(event){if($('[data-ad-entity="aa_lb_03_general_desktop"]').length>0){var ad=$('[data-ad-entity="aa_lb_03_general_desktop"]'),blocks=$('.region-featured-right.column-lg-4 .block');$('.region-featured-right.column-lg-4 .desktop-show.db35dd80-7a3f-4734-a9ce-ead26fe51ea2').remove();adjustRightRailForAd(ad,blocks);}}
function shiftRightRailForREC_03(event){var ad=$('[data-ad-entity="ad_entity_dfp_rec_03_article_desktop"]');if(ad.length>0){var blocks=$('.region-featured-right .block');$('.region-featured-right .desktop-show.db35dd80-7a3f-4734-a9ce-ead26fe51ea2').remove();adjustRightRailForAd(ad,blocks);}}
if(settings.noAds!=1&&$('body.page-node-type-article .layout-container.aa-full-article-page').length<1){advertisementReposition();advertisementRepositionInlineParagraph();$(window).on('load',advertisementReposition);$(window).on('load',advertisementRepositionInlineParagraph);if(settings.site_code=='aac'){if(window.googletag&&['narrow','desktop'].indexOf(window.themeBreakpoints.currentBreakpoint.name)>-1){window.googletag.cmd.push(function(){window.googletag.pubads().addEventListener('slotVisibilityChanged',aacShiftRightRailForLB_03,false);});}}
if(($.inArray(settings.site_code,['ccb','ccl','cdb','cny'])>-1)){if(window.googletag&&['narrow','desktop'].indexOf(window.themeBreakpoints.currentBreakpoint.name)>-1){window.googletag.cmd.push(function(){window.googletag.pubads().addEventListener('slotVisibilityChanged',shiftRightRailForREC_03,false);});}}}}};})(window.adEntity,jQuery,Drupal,drupalSettings);;/*!
* jQuery throttle / debounce - v1.1 - 3/7/2010
* http://benalman.com/projects/jquery-throttle-debounce-plugin/
*
* Copyright (c) 2010 "Cowboy" Ben Alman
* Dual licensed under the MIT and GPL licenses.
* http://benalman.com/about/license/
*/(function(window,undefined){'$:nomunge';var $=window.jQuery||window.Cowboy||(window.Cowboy={}),jq_throttle;$.throttle=jq_throttle=function(delay,no_trailing,callback,debounce_mode){var timeout_id,last_exec=0;if(typeof no_trailing!=='boolean'){debounce_mode=callback;callback=no_trailing;no_trailing=undefined;}
function wrapper(){var that=this,elapsed=+new Date()-last_exec,args=arguments;function exec(){last_exec=+new Date();callback.apply(that,args);};function clear(){timeout_id=undefined;};if(debounce_mode&&!timeout_id){exec();}
timeout_id&&clearTimeout(timeout_id);if(debounce_mode===undefined&&elapsed>delay){exec();}else if(no_trailing!==true){timeout_id=setTimeout(debounce_mode?clear:exec,debounce_mode===undefined?delay-elapsed:delay);}};if($.guid){wrapper.guid=callback.guid=callback.guid||$.guid++;}
return wrapper;};$.debounce=function(delay,at_begin,callback){return callback===undefined?jq_throttle(delay,at_begin,false):jq_throttle(delay,callback,at_begin!==false);};})(this);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_custom_work_js={attach:function(context,settings){var topClass='block-region-content-top',bottomClass='block-region-content-bottom',workCreditClass='work-field-node-field-tags',uninitializedAdClass='initialization-disabled',adBlock='[data-block-plugin-id^="ad_display"]',uninitializedAds=$('.'+uninitializedAdClass),topBlockAds=$('.'+topClass+' > '+adBlock),bottomBlockAds=$('.'+bottomClass+' > '+adBlock),creditBlock=$('.'+bottomClass+' > '+'.'+workCreditClass),isSensitiveContent=settings.is_sensitive_content||0,isLoggedIn=typeof window.Crain.visitor!=='undefined'?window.Crain.visitor.isLoggedIn:false,isSponsoredContent=settings.is_sponsored_content,isSponsoredWorkContent=settings.is_sponsored_work_content,aco_tags=null,aao_tags=null,guid=null;if(isLoggedIn){if(User.user&&User.user.Memebership&&User.user.Memebership.tier){var userMemberTier=User.user.Membership.tier;}}
if(drupalSettings.hasOwnProperty('aco_tags')){aco_tags=drupalSettings.aco_tags;aco_tags=aco_tags.length==1?aco_tags[0]:aco_tags;}
if(drupalSettings.hasOwnProperty('aao_tags')){aao_tags=drupalSettings.aao_tags;if(document.referrer.indexOf('https://t.co/')>=0){aao_tags.push('t.co');}
aao_tags=aao_tags.length==1?aao_tags[0]:aao_tags;}
if(drupalSettings.hasOwnProperty('dfp_ads_custom')){guid=drupalSettings.dfp_ads_custom.targeting.guid;}
$($(document),context).once('aacAdjusttopbottom').each(function(){if(topBlockAds.length>0){$('.'+topClass).prepend(topBlockAds);}
if(bottomBlockAds.length>0){if(creditBlock.length>0){$(bottomBlockAds[0]).insertAfter(creditBlock);}
else{$('.'+bottomClass).prepend($(bottomBlockAds[0]));}}});$.each(uninitializedAds,function(idx,adElement){var $adElement=$(adElement),targeting=JSON.parse($adElement.attr('data-ad-entity-targeting'))||targeting;if(aco_tags!=null){targeting.aco_cat=aco_tags||'';}
if(aao_tags!=null){targeting.aao_cat=aao_tags||'';}
if(guid!=null){targeting.guid=guid||'';}
targeting.q=userMemberTier||'';if(isSensitiveContent==1){targeting.sc='y';}
if(isSponsoredContent!=null){targeting.aco_sponsor=isSponsoredWorkContent;}
$adElement.attr('data-ad-entity-targeting',JSON.stringify(targeting));});if(isSensitiveContent==1){window.googletag.pubads().setTargeting('sc','y');}
if(isSponsoredContent!=null){window.googletag.pubads().setTargeting('aco_sponsor',isSponsoredWorkContent);}}};})(window.adEntity,jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.dfp_initialize={attach:function(context,settings){$(window).on('paywall-show-as-inline.show_paywall paywall-show.show_paywall',function(e){$('.article-paragraph p').not(':first').remove();$(window).off(e.type+'.show_paywall');});if(settings.noAds!=1){function callInitialize(){var callInitialized=true;if(typeof settings.crain_object=='object'&&typeof settings.crain_object.content=='object'&&typeof settings.crain_object.content.AccessControl=='object'&&!$.isEmptyObject(settings.crain_object.content.AccessControl)){callInitialized=false;}
if(typeof settings.disable_ip_access!='undefined'){callInitialized=true;}
return callInitialized;};function moatResetTargeting(uninitializedAd,allVariants,$constraint){var variants={};$.each(uninitializedAd,function(idx,adElement){var $adElement=$(adElement),$targeting='';if($constraint){if($adElement.attr('data-ad-entity-targeting').indexOf($constraint)>-1){$adElement.removeClass(uninitializedAdClass);}
else{$adElement.addClass('paywall-show');}}
else{$adElement.removeClass(uninitializedAdClass);}
if(allVariants.hasOwnProperty(adElement.id)&&!$(adElement).hasClass(uninitializedAdClass)){variants[adElement.id]=allVariants[adElement.id];$targeting=$adElement.attr('data-ad-entity-targeting');if($targeting){try{$targeting=JSON.parse($targeting);$targeting.referrer=document.referrer.split("?")[0].slice(-40);if($.inArray(settings.site_code,['cgweb','c360dx','cpon'])>-1){$targeting.newsletter_campaign=getFirstUrlParameter("utm_nl_name","utm_campaign");}
var utmArray=["utm_campaign","utm_medium","utm_source"];utmArray.forEach(function(utm){$targeting[utm]=getFirstUrlParameter(utm);});$adElement.attr('data-ad-entity-targeting',JSON.stringify($targeting));if(drupalSettings.hasOwnProperty('global_ad_key_value_pairs')&&Object.getOwnPropertyNames(drupalSettings.global_ad_key_value_pairs).length>0){$(window).on('dfp:BeforeDisplay',function(event){var key;var tagettingArray=['tag','subchannel','channel'];for(key in event.detail.targeting){if((jQuery.inArray(key,tagettingArray)!==-1)&&(event.detail.targeting[key].indexOf('[')>=0)){try{event.detail.targeting[key]=JSON.parse(event.detail.targeting[key]);}
catch($e){}}}});_.extend($targeting,drupalSettings.global_ad_key_value_pairs);}
variants[adElement.id].data('data-ad-entity-targeting',$targeting);}
catch($e){}}}});if(!$.isEmptyObject(variants)){var notInitializedVariants={};$.each(variants,function(idx,adVariant){if(!$(adVariant.el).hasClass('initialized')){notInitializedVariants[idx]=adVariant;}});if(!$.isEmptyObject(notInitializedVariants)){if(settings.dfp_idio_script==1){$(window).on('ido-dfp-finished',function(){ad_entity.restrictAndInitialize(notInitializedVariants,context,settings);});}
else{ad_entity.restrictAndInitialize(notInitializedVariants,context,settings);}}}}
function resetTargeting(uninitializedAd,allVariants,$constraint){if(window.mostYieldReadyFired||settings.crain_no_moat_ads==1){if(window.moatPrebidApi){$(window).on('dfp:BeforeDisplay',function(event){if(event&&event.detail&&event.detail.slot&&event.detail.targeting){window.moatPrebidApi.setMoatTargetingForSlot(event.detail.slot,event.detail.targeting.pos);}});}
moatResetTargeting(uninitializedAd,allVariants,$constraint);}
else{window.moatYieldReady=function(){$(window).on('dfp:BeforeDisplay',function(event){if(event&&event.detail&&event.detail.slot&&event.detail.targeting){window.moatPrebidApi.setMoatTargetingForSlot(event.detail.slot,event.detail.targeting.pos);}})
moatResetTargeting(uninitializedAd,allVariants,$constraint);};}}
var getFirstUrlParameter=function(){var names=Array.prototype.slice.call(arguments);for(var i=0;i<names.length;i++){var re=new RegExp(names[i]+'=([^&#=]*)');var result=re.exec(window.location.search);if(result&&typeof result[1]==='string'){return result[1];}}
return '';};var uninitializedAdClass='initialization-disabled',uninitializedAd=$('.'+uninitializedAdClass),allVariants=$.extend({},ad_entity.collectAdContainers(context,settings),ad_entity.adContainers);if(uninitializedAd.length>0){var targetingSet=false;if(callInitialize()){$(window).on('crain-clickshare-targeting-set.show_ads',function(e){switch(e.type){case 'crain-clickshare-targeting-set':targetingSet=true;break;}
$(window).off(e.type+'.show_ads');if(targetingSet){resetTargeting(uninitializedAd,allVariants);}});}
else{var showNotShowPaywall=false,showShowPaywall=false;$(window).on('crain-paywall-not-show.show_ads crain-paywall-in-place-show.show_ads paywall-not-show.show_ads crain-clickshare-targeting-set.show_ads paywall-show-as-inline.show_ads',function(e){switch(e.type){case 'crain-paywall-not-show':case 'paywall-not-show':case 'crain-paywall-in-place-show':showNotShowPaywall=true;break;case 'crain-clickshare-targeting-set':targetingSet=true;break;case 'paywall-show-as-inline':showShowPaywall=true;break;}
if(e.type=='crain-paywall-in-place-show'){uninitializedAd=$('.'+uninitializedAdClass);}
$(window).off(e.type+'.show_ads');if(targetingSet){if(showNotShowPaywall){allVariants=$.extend({},ad_entity.collectAdContainers(context,settings),ad_entity.adContainers);resetTargeting(uninitializedAd,allVariants);}
else if(showShowPaywall){resetTargeting(uninitializedAd,allVariants,'LB_01');var resetTopSize=function(){var topRegion=$('[data-block-plugin-id="system_breadcrumb_block"]');if(topRegion.length!=0){var top=parseFloat(topRegion.css('height'))+topRegion.offset().top;$('.porte-modal-obstruct').css({'top':top+'px'});}};resetTopSize();$(window).resize($.debounce(100,resetTopSize));if(window.googletag){window.googletag.cmd.push(function(){window.googletag.pubads().addEventListener('slotRenderEnded',$.debounce(100,resetTopSize),false);});}}}});}}
if(['cmhdh','cmh'].indexOf(settings.site_code)>-1){var sponsoreContent='.region-featured-right .sponsored-content-block';if($(sponsoreContent).length>0){window.addEventListener('adEntity:initialized',function(evt){if(evt.detail.container.ad_tag.data('data-dfp-sizes').indexOf('fluid')&&$(evt.detail.container.el).hasClass('empty')){setTimeout(function(){if($(sponsoreContent).find('.ad-entity-container').length==$(sponsoreContent).find('.ad-entity-container.empty').length){$(sponsoreContent).addClass('hidden');}},1000);}});}}}}}})(window.adEntity,jQuery,Drupal,drupalSettings);;(function(ad_entity,$,Drupal,drupalSettings){Drupal.behaviors.crain_clickshare_ad_targeting={attach:function(context,settings){var clickShareKeyValue={settings:settings.clickshareKeyValueObject&&settings.clickshareKeyValueObject.clickShareValue?JSON.parse(settings.clickshareKeyValueObject.clickShareValue):{}};var enableDisableClickshareValue=settings.enableDisableClickshareUsertargeting;clickShareKeyValue.userCheckExisted=function(props){var obj=window;$.each(props,function(key,val){if(obj&&obj.hasOwnProperty(val)){obj=obj[val];}
else{obj="";return;}});return obj;};clickShareKeyValue.setClickshareKeyValue=function(key,obj,customVariables,scope){obj=obj||'';if(obj.length>40){obj=obj.substring(0,40);}
var clickShareTargetingObject={};var allVariants=$.extend({},ad_entity.collectAdContainers(context,settings),ad_entity.adContainers);$.each(allVariants,function(idx,adElement){var $adElement=$(adElement.el),$targeting='';$targeting=$adElement.attr('data-ad-entity-targeting');if($targeting){try{$targeting=JSON.parse($targeting);clickShareTargetingObject[key]=obj;_.extend($targeting,clickShareTargetingObject);$adElement.attr('data-ad-entity-targeting',JSON.stringify($targeting));}
catch($e){}}});}
clickShareKeyValue.iteratehasKey=function(obj,key,res){if(typeof obj=='array'||typeof obj=='object'){if(obj.hasOwnProperty(key)){res.push(obj[key]);}
else{$.each(obj,function(subkey,val){clickShareKeyValue.iteratehasKey(val,key,res);});}}}
clickShareKeyValue.iteratehasKeyObj=function(obj,key,target){if(typeof obj=='array'||typeof obj=='object'){if(obj.hasOwnProperty(key)&&(typeof obj[key]=='string')){target.push(obj[key]);}
else{$.each(obj,function(subkey,val){clickShareKeyValue.iteratehasKeyObj(val,key,target);});}}}
clickShareKeyValue.clickshareKeyValueObjEqual=function(obj,key,target){if(typeof obj=='array'||typeof obj=='object'){$.each(obj,function(subkey,val){clickShareKeyValue.clickshareKeyValueObjEqual(val,key,target);});}
else if(obj==key){target.push(key);}}
clickShareKeyValue.setClickshareKeyValueIterator=function(parentObj){var op=parseInt(parentObj.js_object_op)||0,jsObj=parentObj.js_object||'',props=parentObj.js_object.split('.'),clickshareKey=parentObj.clickshare_key||'',pianoCustomVariables=parentObj.piano_custom_variables||false,jsobjectValue=parentObj.js_object_value||'',scope=parentObj.param_object_scope||'',trueObj=parentObj.true_value||'',falseObj=parentObj.false_value||'';if(clickshareKey&&jsObj){var obj=clickShareKeyValue.userCheckExisted(props);switch(op){case 0:clickShareKeyValue.setClickshareKeyValue(clickshareKey,obj,pianoCustomVariables);break;case 5:if(obj==jsobjectValue){clickShareKeyValue.setClickshareKeyValue(clickshareKey,obj,jsobjectValue);}
else{clickShareKeyValue.setClickshareKeyValue(clickshareKey,falseObj,pianoCustomVariables);}
break;}}}
clickShareKeyValue.checkTruexUnlock=function(){var unlocks=[];if(localStorage.getItem("unlocks")){unlocks=JSON.parse(localStorage.getItem("unlocks"));}
var unlocksCopy=[];var url=location.origin+location.pathname;var urlIsUnlocked=false;for(var i in unlocks){if(unlocks[i].url===url){urlIsUnlocked=true;break;}}
for(var i in unlocks){var storageYear=new Date(unlocks[i].added).getFullYear();var currentYear=new Date().getFullYear();var storageMonth=new Date(unlocks[i].added).getMonth();var currentMonth=new Date().getMonth();if((storageYear==currentYear)&&(storageMonth==currentMonth)){unlocksCopy.push(unlocks[i]);}}
localStorage.setItem('unlocks',JSON.stringify(unlocksCopy));User=User||[];User.truexUnlocked=urlIsUnlocked+'';User.truexCount=unlocksCopy.length+'';};if(clickShareKeyValue.settings&&enableDisableClickshareValue){var clickshareKeyValueObject=clickShareKeyValue.settings,userClickshareKeyValueObj=[];$.each(clickshareKeyValueObject,function(key,val){if(val.js_object.split('.')[0]!=='User'){clickShareKeyValue.setClickshareKeyValueIterator(val);}else{userClickshareKeyValueObj.push(val);}});$(window).on('user-object-created.clickshare_dfp',function(){$(window).off('user-object-created.clickshare_dfp');clickShareKeyValue.checkTruexUnlock();$.each(userClickshareKeyValueObj,function(key,val){clickShareKeyValue.setClickshareKeyValueIterator(val);});$(window).trigger('crain-clickshare-targeting-set');});}
else{$(window).trigger('crain-clickshare-targeting-set');}}}})(window.adEntity,jQuery,Drupal,drupalSettings);;(function($,Drupal,drupalSettings){Drupal.behaviors.onesignal_lazy_load={attach:function(context,settings){function loadScript(url,callback){var script=document.createElement("script")
script.type="text/javascript";if(script.readyState){script.onreadystatechange=function(){if(script.readyState==="loaded"||script.readyState==="complete"){script.onreadystatechange=null;callback();}};}else{script.onload=function(){callback();};}
script.src=url;document.getElementsByTagName("head")[0].appendChild(script);}
$(window).one("scroll",function(){if(typeof window.OneSignal==='function'||typeof window.OneSignal!=='undefined'){return;}
loadScript("https://cdn.onesignal.com/sdks/OneSignalSDK.js",function(){var OneSignal=window.OneSignal||[];OneSignal.push(function(){OneSignal.init({appId:settings.crain_onesignal_id});});});});}}})(jQuery,Drupal,drupalSettings);;