Drupal.nextgen_auth=(function(){Drupal.behaviors.nextgen_auth={attach:function(context,settings){var url=window.location.href;if(url.indexOf('ng_gateway_return=')!==-1){var custom_base_url=url.split('?')[0];const queryString=typeof url.split('?')[1]!==undefined?url.split('?')[1]:null;if(queryString!==null){var searchParams=new URLSearchParams(queryString);var newqueryString='';for(let p of searchParams){if(p[0]!="ng_gateway_return"&&p[0]!='full'&&p[0]!='token'){newqueryString=(newqueryString!='')?newqueryString+'&'+p[0]+'='+p[1]:p[0]+'='+p[1];}}
const finalModifiedURL=custom_base_url+(newqueryString!=''?'?'+newqueryString:'');window.history.replaceState(null,null,finalModifiedURL);}}
nextgen_auth.UI.getInstance().init();nextgen_auth.UI.bindActions(document.body);}};var nextgen_auth=function(){this.options={cookie_3pc_key:'3pc_set',ng_endpoint:Drupal.settings.nextgen_auth.ng_endpoint||"https://ngi-dev.techweb.com"};Drupal.settings['nextgen_auth_modal']={animation:'fadeIn',closeText:'close',modalOptions:{background:'#000',opacity:0.85},modalSize:{height:200,width:350,type:"fixed"},modalTheme:"ModalFormsPopup"};};nextgen_auth.applyConfig=function(object,config,defaults){if(defaults){nextgen_auth.applyConfig(object,defaults);}
if(object&&config&&typeof config==='object'){for(var i in config){object[i]=config[i];}}
return object;};nextgen_auth.prototype.getCookie=function(name){var re=new RegExp(name+"=([^;]+)");var value=re.exec(document.cookie);return(value!=null)?unescape(value[1]):null;};nextgen_auth.prototype.setCookie=function(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/;secure;";};nextgen_auth.prototype.cookieTest=function(callback){var self=this;var cookie=this.getCookie(this.options.cookie_3pc_key);if(cookie){if(typeof(callback)=='function'){callback(null,cookie,true);}
return;}
return;};nextgen_auth.gatewayCallback=function(error,data){if(error){Drupal.CTools.Modal.show('nextgen_auth_modal');jQuery('#modal-title').html('Authentication Error');jQuery('#modal-content').html('Unable to authenticate with gateway: '+error);return;}
else if(typeof(data)=='undefined'||data===false||data===null){return;}
if(data){location.reload(true);}};nextgen_auth.openReg=function(config){var config=config||{};var w=nextgen_auth.UI.getWindow('regFormWindow',nextgen_auth.applyConfig({title:'Registrations',},config,{width:600,height:800,modal:true}));nextgen_auth.UI.Window.openFormToWindow(w,'/ng/user/register',null,null,function(resp){if(resp.success){location.reload(true);}})};nextgen_auth.openAssetDownloadQA=function(config){var config=config||{};var w=nextgen_auth.UI.getWindow('regFormWindow',nextgen_auth.applyConfig({title:'Registrations',},config,{width:600,height:800,modal:true}));var uripromo='';if(typeof window.cid!='undefined'){uripromo='&cid='+window.cid;}
if(typeof window._mc!='undefined'){uripromo+='&_mc='+window._mc;}
if(typeof window.accessToken!='undefined'){uripromo+='&accessToken='+window.accessToken;}
api_uri='/ng/user/asset/download/';if(typeof window.viaAccessToken!='undefined'){uripromo+='&accessToken='+window.accessToken;api_uri='/ng/user/asset/download_via_acccesstoken/';}
nextgen_auth.UI.Window.openFormToWindow(w,api_uri+window.asset_id+"?f="+window.fid+"&rid="+window.resource+"&refrid="+window.refResource+uripromo,null,null,function(resp){if(resp.success){nextgen_auth.UI.Window.current_window.close();window.localStorage.removeItem("download_asset_intent");window.location=window.assetDownloadUrl;}})};nextgen_auth.openAssetDisplayQA=function(config){var config=config||{};var w=nextgen_auth.UI.getWindow('regFormWindow',nextgen_auth.applyConfig({title:'Registrations',},config,{width:600,height:800,modal:true}));var uripromo='';if(typeof window.cid!='undefined'){uripromo='&cid='+window.cid;}
if(typeof window._mc!='undefined'){uripromo+='&_mc='+window._mc;}
if(typeof window.accessToken!='undefined'){uripromo+='&accessToken='+window.accessToken;}
nextgen_auth.UI.Window.openFormToWindow(w,'/ng/user/asset/download/'+window.asset_id+uripromo,null,null,function(resp){if(resp.success){nextgen_auth.UI.Window.current_window.close();var accordionid=window.podcastlinkDom.attr('playerdivid');if(window.last_playing_podcast!=null){var cont=jQuery(window.last_playing_podcast).html();jQuery(window.last_playing_podcast).html("");jQuery(window.last_playing_podcast).html(cont);}
window.collapsiblePodcastDivs.collapse('hide');jQuery(accordionid).collapse('show');}})};nextgen_auth.openPasswordReset=function(config){var config=config||{};var w=nextgen_auth.UI.getWindow('pwResetWindow',nextgen_auth.applyConfig({title:'Password Reset',},config,{width:600,height:400,modal:true,offsetY:-200}));nextgen_auth.UI.Window.openFormToWindow(w,'/ng/password/reset',null,null,function(resp){})};nextgen_auth.openLogin=function(config){var config=config||{};var w=nextgen_auth.UI.getWindow('loginWindow',nextgen_auth.applyConfig({title:'Login',},config,{width:600,height:500,modal:true,offsetY:-200,showTitleBar:true}));var messages=null;var dest=config.dest||window.location.href;if(typeof(config.messages)=='string'){messages=[{type:'status',message:config.messages}];}
else if(typeof(config.messages)=='object'&&config.messages.length>0){messages=config.messages;}
nextgen_auth.UI.Window.openFormToWindow(w,'/ng/user/login',messages,dest,function(resp){if(resp.success){location.reload(true);}})};nextgen_auth.openGate=function(config){var w=nextgen_auth.UI.getWindow('gateWindow',nextgen_auth.applyConfig({},config,{title:'',width:700,height:500,modal:true,offsetY:-200,showTitleBar:false}));nextgen_auth.UI.Window.openContentToWindow(w,'/ng/content/gate');};nextgen_auth.UI=function(config){if(nextgen_auth.UI._instance){return nextgen_auth.UI._instance;}
if(!(this instanceof nextgen_auth.UI)){return new nextgen_auth.UI();}
nextgen_auth.UI._instance=this;this.windows={};this._events={};};nextgen_auth.UI.getInstance=function(){return new nextgen_auth.UI();};nextgen_auth.UI.on=function(event,func){var instance=nextgen_auth.UI.getInstance();instance.on(event,func);};nextgen_auth.UI.prototype.on=function(event,func){if(typeof(func)!=='function')return;if(typeof(this._events[event])=='undefined'){this._events[event]=[];}
this._events[event].push(func);};nextgen_auth.UI.prototype.emit=function(evt){if(typeof(this._events[evt])=='undefined')return;var events=this._events[evt];for(var i=0;i<events.length;i++){var args=Array.prototype.slice.call(arguments);args.shift();events[i].apply(this,args);}};nextgen_auth.UI.actionHandler=function(event){var action=jQuery(this).attr('x-ng-ui-action');if(action){var instance=nextgen_auth.UI.getInstance();instance.emit(action,this);}
event.preventDefault();};nextgen_auth.UI.bindActions=function(container){jQuery('.x-ng-ui-action',container).bind('click',nextgen_auth.UI.actionHandler);};nextgen_auth.UI.unbindActions=function(container){jQuery('.x-ng-ui-action',container).unbind();};nextgen_auth.UI.prototype.init=function(){var self=this;jQuery(window).resize(function(e){for(var i in self.windows){if(!self.windows.hasOwnProperty(i))continue;var w=self.windows[i];if(w instanceof nextgen_auth.UI.Window&&w._state.opened){w.onViewportResize(e);}}})
this.on('close_window',function(elm){if(nextgen_auth.UI.Window.current_window){nextgen_auth.UI.Window.current_window.close();}});this.on('open_reg',function(elm){nextgen_auth.openReg()});this.on('open_pw_reset',function(elm){nextgen_auth.openPasswordReset();});this.on('open_login',function(elm){nextgen_auth.openLogin();});};nextgen_auth.UI.getWindow=function(name,config){var self=new nextgen_auth.UI();if(self.windows[name]){return self.windows[name];}
var w=nextgen_auth.UI.Window.create(config);self.windows[name]=w;return w;};nextgen_auth.UI.Window=function(config){this.title=config.title||'';this.width=config.width||640;this.height=config.height||460;this.id='ng-auth-ui-window-'+(config.id||(new Date().getTime()).toString(36));this.className='ng-auth-ui-window '+(config.className||'');this.type=config.type||'fixed-modal';this.destroyOnClose=typeof(config.destroyOnClose)=='boolean'?config.destroyOnClose:false;this.content=config.content||'';this.closeHandler=typeof(config.closeHandler)=='function'?config.closeHandler:null;this.modal=typeof(config.modal)=='boolean'?config.modal:false;this.showTitleBar=typeof(config.showTitleBar)=='boolean'?config.showTitleBar:true;this.offsetX=config.offsetX||0;this.offsetY=config.offsetY||0;this.closable=typeof(config.closable)=='boolean'?config.closable:true;this._elements={body:null,topbar:null,topbarTitle:null,topbarCloseButton:null,overlay:null,loadingScreen:null};this._state={opened:false};};nextgen_auth.UI.Window.current_window=null;nextgen_auth.UI.Window.create=function(config){var w=new nextgen_auth.UI.Window(config);return w;};nextgen_auth.UI.Window.prototype.init=function(){var divElm=document.createElement('div');divElm.id=this.id;divElm.style.display='none';divElm.className=this.className.trim()+' ng-auth-ui-window-'+this.type;var bodyDiv=document.createElement('div');bodyDiv.className='ng-auth-ui-window-body';this._elements.body=bodyDiv;if(this.content&&this.content.length>0){bodyDiv.innerHTML=this.content;}
if(this.width){divElm.style.width=this.width+'px';}
if(this.height){divElm.style.height=this.height+'px';}
var topBarElement=document.createElement('div');topBarElement.className='ng-auth-ui-window-topbar';this._elements.topbar=topBarElement;if(!this.showTitleBar){topBarElement.style.display='none';}
var topBarTitleElement=document.createElement('span');topBarTitleElement.className='ng-auth-ui-window-topbar-title';this._elements.topbarTitle=topBarTitleElement;if(this.title&&this.title.length>0){topBarTitleElement.innerHTML=this.title;}
var topBarCloseButtonElement=document.createElement('span');topBarCloseButtonElement.className='x-ng-ui-action ng-auth-ui-window-topbar-cbtn';topBarCloseButtonElement.setAttribute('x-ng-ui-action','close_window');topBarCloseButtonElement.innerHTML='X';this._elements.topbarCloseButton=topBarCloseButtonElement;var overlayLayer=document.getElementById('ng-auth-ui-overlay');if(!overlayLayer){overlayLayer=document.createElement('div');overlayLayer.id='ng-auth-ui-overlay';overlayLayer.className='ng-auth-ui-overlay-layer';overlayLayer.style.display='none';document.body.appendChild(overlayLayer);}
this._elements.overlay=overlayLayer;var loadingScreen=document.createElement('div');loadingScreen.className='ng-auth-ui-window-loading';loadingScreen.innerHTML='<img src="/'+Drupal.settings.nextgen_auth.image_path+'/loading.gif" />';loadingScreen.style.display='none';divElm.appendChild(loadingScreen);this._elements.loadingScreen=loadingScreen;topBarElement.appendChild(topBarTitleElement);if(this.closable){topBarElement.appendChild(topBarCloseButtonElement);}
divElm.appendChild(topBarElement);divElm.appendChild(bodyDiv);document.body.appendChild(divElm);nextgen_auth.UI.bindActions(divElm);};nextgen_auth.UI.Window.prototype.getWindowElement=function(create){var elm=document.getElementById(this.id)
if(!elm&&create===true){this.init();elm=document.getElementById(this.id);}
return elm;};nextgen_auth.UI.Window.prototype.rebindBody=function(){if(this._elements.body){nextgen_auth.UI.bindActions(this._elements.body);}};nextgen_auth.UI.Window.prototype.setContent=function(content){this.content=content;var w=this.getWindowElement();if(w&&this._elements.body){this._elements.body.innerHTML=content;}};nextgen_auth.UI.Window.prototype.setLoading=function(bool){if(this._elements.loadingScreen){this._elements.loadingScreen.style.display=bool?'block':'none';}};nextgen_auth.UI.Window.prototype.show=function(){if(nextgen_auth.UI.Window.current_window){if(nextgen_auth.UI.Window.current_window===this)return;nextgen_auth.UI.Window.current_window.close();}
var w=this.getWindowElement(true);if(w){this.updatePosition();w.style.display='block';}
if(this._elements.overlay&&this.modal){this._elements.overlay.style.display='block';}
this._state.opened=true;nextgen_auth.UI.Window.current_window=this;};nextgen_auth.UI.Window.prototype.close=function(){var w=this.getWindowElement();if(!w)return;if(this.destroyOnClose){this.destroy();}
else{w.style.display='none';}
if(this._elements.overlay){this._elements.overlay.style.display='none';}
this._state.opened=false;nextgen_auth.UI.Window.current_window=null;};nextgen_auth.UI.Window.prototype.onViewportResize=function(e){this.updatePosition();};nextgen_auth.UI.Window.prototype.updatePosition=function(){var w=this.getWindowElement();if(!w)return;var viewportWidth=window.innerWidth;var viewportHeight=window.innerHeight;var xMid=viewportWidth>>1;var yMid=viewportHeight>>1;if(this.width){var left=(xMid-(this.width>>1))-(this.offsetX);w.style.left=left>0?left+'px':0;}
if(this.height){var top=(yMid-(this.height>>1))+(this.offsetY);w.style.top=top>0?top+'px':0;}
if(viewportWidth<this.width){jQuery(w).addClass('ng-auth-ui-window-fit');}
else{jQuery(w).removeClass('ng-auth-ui-window-fit');}};nextgen_auth.UI.Window.prototype.destroy=function(){var w=this.getWindowElement();if(w){nextgen_auth.UI.unbindActions(w);w.parentNode.removeChild(w);}};nextgen_auth.UI.Window.openContentToWindow=function(wnd,url){wnd.show();wnd.setLoading(true);jQuery.ajax({url:url,success:function(result){wnd.setLoading(false);wnd.setContent(result.html);wnd.rebindBody();}});};nextgen_auth.UI.Window.openFormToWindow=function(wnd,url,msgs,dest,submitSuccess){var loadScripts=function(scripts){var js=[];var inlines=[];for(var k in scripts){if(!scripts.hasOwnProperty(k)){continue;}
var att=scripts[k];if(typeof(att)=='string'){js.push(att);}
else if(att.type&&att.type=='inline'){inlines.push(k);}}
if(js.length>0){for(var i=0;i<js.length;i++){jQuery.getScript('/'+js[i],function(){for(var j=0;j<inlines.length;j++){eval(inlines[j]);}});}}};var bindForm=function(f){f.submit(function(event){var form=jQuery(this);wnd.setLoading(true);var action=form.attr('action');if(typeof(dest)=='string'){action+="?dest="+encodeURIComponent(dest);}
jQuery.ajax({type:'POST',url:action,data:form.serialize(),success:function(resp){wnd.setLoading(false);if(resp.errors){wnd.setContent(resp.html);var windowElement=wnd.getWindowElement()
jQuery('a',windowElement).each(function(){var anch=jQuery(this);if(typeof(anch.attr('x-ng-ui-action'))=='undefined'){var link=anch.attr('href');if(link&&link.match(/^\/user\/password/)){anch.attr('x-ng-ui-action','open_pw_reset');anch.addClass('x-ng-ui-action');}}});bindForm(jQuery('#'+wnd.id+' form'));wnd.rebindBody();loadScripts(resp.js);setMessages(msgs);}
else{if(typeof(submitSuccess)=='function'){submitSuccess.call(this,resp);}}}});event.preventDefault();})};var setMessages=function(messages){if(messages!==null&&typeof(messages)=='object'&&messages.length>0){var windowElement=wnd.getWindowElement();for(var i=0;i<messages.length;i++){var msg=messages[i];jQuery('ul.messages-list',windowElement).append('<li class="'+msg.type+'">'+msg.message+'</li>');}}};wnd.show();wnd.setLoading(true);jQuery.ajax({url:url,success:function(result){wnd.setLoading(false);wnd.setContent(result.html);bindForm(jQuery('#'+wnd.id+' form'));wnd.rebindBody();if(result.js){loadScripts(result.js);}
setMessages(msgs);},error:function(result){wnd.close();}});};return nextgen_auth;})();;(function($){containsAny=function(arr,values){return _.some(values,function(value){return _.contains(arr,value);});},isEmail=function(email){var format=/^[a-zA-Z0-9\-_]+(\.[a-zA-Z0-9\-_]+)*@[a-z0-9]+(\-[a-z0-9]+)*(\.[a-z0-9]+(\-[a-z0-9]+)*)*\.[a-z]{2,4}$/;return!!email.match(format);},isNumeric=function(str){var isNumeric=/^[-+]?(\d+|\d+\.\d*|\d*\.\d+)$/;return isNumeric.test(str);},isCookie=function(name){var cookies=document.cookie.split(";")
for(var i=0,ilen=cookies.length;i<ilen;i++){var cookie=cookies[i].split("=")
if(name==cookie[0]){return true;}}
return false;},count=function(obj){var i=0;for(var x in obj){if(obj.hasOwnProperty(x)){i++;}}
return i;},typeOf=function(query){if(typeof query!=='string'){return;}
window.hasOwnProperty=window.hasOwnProperty||Object.prototype.hasOwnProperty
var pointer=window;var parts=query.split('.');var part;for(i in parts){part=parts[i];if(!pointer.hasOwnProperty(part)){return undefined;}
pointer=pointer[part];}
return typeof pointer;},inIframe=function(){try{return window.self!==window.top;}catch(e){return true;}}})(jQuery);;Drupal.platform_podcast=Drupal.platform_podcast||{};window.podcastlinkDom=null;window.collapsiblePodcastDivs=null;window.asset_id='';window.last_playing_podcast=null;jQuery(document).ready(function($){$('a.podcastlink').each(function(){if($(this).attr('href')!=''&&location.pathname.indexOf($(this).attr('href'))>-1&&(window.asset_id==''||window.asset_id!=$(this).attr('asset'))){window.asset_id=$(this).attr('asset');$(this).click();}});});(function($){Drupal.platform_podcast.url='';Drupal.behaviors.platform_podcast={attach:function(context,settings){$('.podcastlink').click(function(e){window.asset_id=$(this).attr('asset');window.cid=$(this).attr('cid');window._mc=$(this).attr('_mc');window.accessToken=$(this).attr('accessToken');var url_postfix_params='?t='+$.now();if(typeof window.cid!='undefined'){url_postfix_params+='&cid='+window.cid;}
if(typeof window._mc!='undefined'){url_postfix_params+='&_mc='+window._mc;}
if(typeof window.accessToken!='undefined'){url_postfix_params+='&accessToken='+window.accessToken;}
if(e.button!=undefined){var link=$(this).attr('href')+url_postfix_params+$(this).attr('playerDivId');window.history.pushState({href:link},'',link);}
e.preventDefault();window.podcast_node=$(this).closest("article").attr('nid');Drupal.platform_podcast.url='/platform_podcast/download/'+window.podcast_node+url_postfix_params;window.assetDownloadUrl=Drupal.platform_podcast.url;var uid=Drupal.nextgen_auth.uid;window.podcastlinkDom=$(this);var accordionid=window.podcastlinkDom.attr('playerDivId');window.collapsiblePodcastDivs=$('.collapse');window.collapsiblePodcastDivs.collapse('hide');if(window.last_playing_podcast!=null){var cont=$(window.last_playing_podcast).html();$(window.last_playing_podcast).html("");}
if(uid){window.podcastlinkDom.attr('disabled','disabled');$.ajax({url:Drupal.platform_podcast.url,dataType:'json',success:function(data){if(data.setAssetForm){Drupal.nextgen_auth.openAssetDisplayQA();}
else{if(window.last_playing_podcast!=null){$(window.last_playing_podcast).html(cont);}
window.last_playing_podcast=accordionid;$(accordionid).collapse('show');}
if(e.button==undefined){document.location.href=accordionid;}
window.podcastlinkDom.removeAttr('disabled');}});}
else{var url=Drupal.settings.basePath+'platform_podcast/log/'
+window.podcast_node+url_postfix_params;$.ajax({url:url,dataType:'json',success:function(data){if(typeof data.setAssetForm!='undefined'&&data.setAssetForm){Drupal.nextgen_auth.openLogin();}
else if(typeof data.setAssetForm!='undefined'){if(window.last_playing_podcast!=null){$(window.last_playing_podcast).html(cont);}
window.last_playing_podcast=accordionid;$(accordionid).collapse('show');}
if(typeof data.set_podcast_nid!='undefined'&&data.set_podcast_nid){Drupal.nextgen_auth.openLogin();}
else{if(window.last_playing_podcast!=null){$(window.last_playing_podcast).html(cont);}
window.last_playing_podcast=accordionid;$(accordionid).collapse('show');if(e.button==undefined){document.location.href=accordionid;}
window.podcastlinkDom.removeAttr('disabled');}}});}});$('#edit-field-gated-whitepaper-nosso-und-0-target-id').blur(function(e){if(!Drupal||!Drupal.jsAC){return true;}
if(this.value){$('#edit-gate-status option').filter(function(){return $.trim($(this).text())=="Inactive";}).attr('selected',true);}});}};$.extend({getQueryParameters:function(str){return(str||document.location.search).replace(/(^\?)/,'').split("&").map(function(n){return n=n.split("="),this[n[0]]=n[1],this}.bind({}))[0];}});})(jQuery);;Drupal.platform_whitepaper=Drupal.platform_whitepaper||{};(function($){Drupal.platform_whitepaper.url='';Drupal.behaviors.platform_whitepaper={attach:function(context,settings){$(document).on('click','.whitepaper',function(e){e.preventDefault();Drupal.platform_whitepaper.checkAssetProcessDownload();});$('#edit-field-gated-whitepaper-nosso-und-0-target-id').blur(function(e){if(!Drupal||!Drupal.jsAC){return true;}
if(this.value){$('#edit-gate-status option').filter(function(){return $.trim($(this).text())=="Inactive";}).attr('selected',true);}});}};Drupal.platform_whitepaper.checkAssetProcessDownload=function(){Drupal.platform_whitepaper.url=$('.whitepaper').attr('href');window.assetDownloadUrl=$('.whitepaper').attr('href');window.cid=$('.whitepaper').attr('cid');window._mc=$('.whitepaper').attr('_mc');window.accessToken=$('.whitepaper').attr('accessToken');var uid=Drupal.nextgen_auth.uid;if(uid){window.asset_id=$('.whitepaper').attr('asset');window.fid=$('.whitepaper').attr('fid');window.resource=$('.whitepaper').attr('resource');window.refResource=$('.whitepaper').attr('refresource');var $pObject=$('.whitepaper');$('#loader').show();$('.whitepaper').attr('disabled','disabled');$.ajax({url:Drupal.platform_whitepaper.url,dataType:'json',success:function(data){if(data.setAssetForm){Drupal.nextgen_auth.openAssetDownloadQA();window.localStorage.setItem("download_asset_intent","1");}
else{window.localStorage.removeItem("download_asset_intent");Drupal.platform_whitepaper.load();}
$('#loader').hide();$pObject.removeAttr('disabled');}});}
else{window.asset_id=$('.whitepaper').attr('asset');window.fid=$('.whitepaper').attr('fid');window.resource=$('.whitepaper').attr('resource');window.refResource=$('.whitepaper').attr('refresource');window.cid=$('.whitepaper').attr('cid');window._mc=$('.whitepaper').attr('_mc');window.accessToken=$('.whitepaper').attr('accessToken');var queryStr='?t='+$.now();if(typeof window.cid!='undefined'){queryStr+='&cid='+window.cid;}
if(typeof window._mc!='undefined'){queryStr+='&_mc='+window._mc;}
if(typeof window.accessToken!='undefined'){queryStr+='&accessToken='+window.accessToken;}
var wp_params=$.getQueryParameters(Drupal.platform_whitepaper.url.split('?')[1]);var url=Drupal.settings.basePath+'platform_whitepaper/log/'
+wp_params.nid+'/'+wp_params.ref_nid+queryStr;$.ajax({url:url,dataType:'json',success:function(data){if(data.setAssetForm==false){window.localStorage.removeItem("download_asset_intent");Drupal.platform_whitepaper.load();}
else if(data.setAssetForm==true&&data.viaAccessToken==true){window.viaAccessToken=true;Drupal.nextgen_auth.openAssetDownloadQA();}
else{Drupal.nextgen_auth.openLogin();window.localStorage.setItem("download_asset_intent","1");}
if(data.set_whitepaper_nid){Drupal.nextgen_auth.openLogin();window.localStorage.setItem("download_asset_intent","1");}
else{}}});}}
Drupal.platform_whitepaper.load=function(){if(Drupal.platform_whitepaper.url==''){Drupal.platform_whitepaper.url=$('.whitepaper').attr('href');}
window.location.replace(Drupal.platform_whitepaper.url);};$.extend({getQueryParameters:function(str){return(str||document.location.search).replace(/(^\?)/,'').split("&").map(function(n){return n=n.split("="),this[n[0]]=n[1],this}.bind({}))[0];}});$(document).ready(function(){if(typeof window.localStorage.getItem("download_asset_intent")!="undefined"&&window.localStorage.getItem("download_asset_intent")=='1'){Drupal.platform_whitepaper.checkAssetProcessDownload();}});})(jQuery);;jQuery(document).ready(function(){jQuery("#edit-field-secondary-keyword-und").change(function(){if(jQuery("#edit-field-secondary-keyword-und").find(":selected").length>5){var count=0;jQuery("#edit-field-secondary-keyword-und").find(":selected").each(function(index){if(count>=5&&jQuery("#edit-field-secondary-keyword-und").find(":selected").length>5){jQuery('#edit-field-secondary-keyword-und option[value="'+jQuery(this).val()+'"]').prop('selected',false);}
count++;});}});});;