(function($,Drupal,drupalSettings){'use strict';Drupal.behaviors.crainLazyloader={attach:function(context,settings){$(document,context).each(function(){if(drupalSettings.crain_lazyloader&&drupalSettings.crain_lazyloader.enabled){const lazyClass=drupalSettings.crain_lazyloader.class;const lazyImg="img."+lazyClass;const picture=[].slice.call(document.querySelectorAll('picture '+lazyImg));let pictureArr=[];picture.forEach(element=>{pictureArr.push(element.parentNode);});let lazyImages=[].slice.call(document.querySelectorAll(lazyImg));if('IntersectionObserver'in window){const config={rootMargin:'250px 0px',};let lazyImageObserver=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){let lazyImage=entry.target;if(!lazyImage.classList.contains('lazyloaded')){if(lazyImage.parentNode.nodeName==='PICTURE'){lazyImage.parentNode.querySelectorAll('source').forEach(source=>{source.srcset=source.dataset.srcset;});lazyImage.parentNode.classList.add('lazyloaded');}
if(typeof lazyImage.dataset.src!=='undefined'){lazyImage.src=lazyImage.dataset.src;}
lazyImageObserver.unobserve(lazyImage);lazyImage.classList.remove(lazyClass);lazyImage.classList.add('lazyloaded');}}});},config);lazyImages.forEach(function(lazyImage){if(!lazyImage.classList.contains('lazyloaded')){lazyImageObserver.observe(lazyImage);}});}
else{lazyImages.forEach(function(lazyImage){lazyImage.src=lazyImage.dataset.src;lazyImage.classList.remove(lazyClass);lazyImage.classList.add('nolazy');});}}});}};}(jQuery,Drupal,drupalSettings));;(function(adEntity,window){adEntity.helpers.trigger=function(target,type,canBubble,cancelable,detail){var event=window.document.createEvent('CustomEvent');if(typeof detail==='undefined'){detail=null;}
event.initCustomEvent(type,canBubble,cancelable,detail);target.dispatchEvent(event);};adEntity.helpers.isEmptyObject=function(obj){var k;for(k in obj){if(obj.hasOwnProperty(k)){return false;}}
return true;};adEntity.helpers.addClass=function(el,className){if(el.classList){el.classList.add(className);}
else{el.className+=' '+className;}};adEntity.helpers.removeClass=function(el,className){if(el.classList){el.classList.remove(className);}
else{el.className=el.className.replace(new RegExp('(^|\\b)'+className.split(' ').join('|')+'(\\b|$)','gi'),' ');}};adEntity.helpers.hasClass=function(el,className){if(el.classList){return el.classList.contains(className);}
else{return new RegExp('(^| )'+className+'( |$)','gi').test(el.className);}};adEntity.helpers.metadata=function(source,target,key,value){var metadata;var length;var i;var attribute;var attribute_value;if(typeof target.__ad_entity_metadata==='undefined'){metadata={};if((typeof source.attributes==='object')&&(typeof source.getAttribute==='function')){length=source.attributes.length;for(i=0;i<length;i++){attribute=source.attributes[i];try{attribute_value=JSON.parse(attribute.value);}
catch(e){attribute_value=attribute.value;}
metadata[attribute.name]=attribute_value;}}
target.__ad_entity_metadata=metadata;}
metadata=target.__ad_entity_metadata;if(typeof key==='undefined'){return metadata;}
if(typeof value!=='undefined'){metadata[key]=value;}
if(metadata.hasOwnProperty(key)){return metadata[key];}};}(window.adEntity,window));;(function(ad_entity,Drupal,window){Drupal.ad_entity=ad_entity;ad_entity.adContainers=ad_entity.adContainers||{};ad_entity.context=ad_entity.context||{};ad_entity.viewHandlers=ad_entity.viewHandlers||{};ad_entity.collectAdContainers=function(context,settings){var newcomers={};var collected=ad_entity.adContainers;var queues=[ad_entity.queue];var queue;var length;var el;var i;var container;var event_detail;ad_entity.queue=[];if(!ad_entity.settings.inline){queues.push(context.querySelectorAll('.ad-entity-container'));}
while(queues.length>0){queue=queues.shift();length=queue.length;for(i=0;i<length;i++){el=queue[i];if(typeof el.id!=='string'||!(el.id.length>0)){continue;}
if(collected.hasOwnProperty(el.id)){continue;}
container={el:el,data:function(key,value){return ad_entity.helpers.metadata(this.el,this,key,value);}};collected[el.id]=container;newcomers[el.id]=container;}}
event_detail={collected:collected,newcomers:newcomers,context:context,settings:settings};ad_entity.helpers.trigger(window,'adEntity:collected',false,true,event_detail);return newcomers;};ad_entity.restrictAdsToScope=function(containers){var helpers=ad_entity.helpers;var scope=['any'];var in_scope;var breakpoint;var container;var container_id;var variant;var variant_length;var el;var i;if(typeof window.themeBreakpoints==='object'){if(typeof window.themeBreakpoints.getCurrentBreakpoint==='function'){breakpoint=window.themeBreakpoints.getCurrentBreakpoint();if(breakpoint){scope.push(breakpoint.name);}}}
in_scope={};for(container_id in containers){if(containers.hasOwnProperty(container_id)){container=containers[container_id];el=container.el;variant=container.data('data-ad-entity-variant');variant_length=variant.length;for(i=0;i<variant_length;i++){if(!(scope.indexOf(variant[i])<0)){in_scope[container_id]=container;if(container.data('inScope')!==true){helpers.addClass(el,'in-scope');helpers.removeClass(el,'out-of-scope');el.style.display=null;container.data('inScope',true);}
break;}}
if(!in_scope.hasOwnProperty(container_id)&&(container.data('inScope')!==false)){helpers.removeClass(el,'in-scope');helpers.addClass(el,'out-of-scope');el.style.display='none';container.data('inScope',false);}}}
return in_scope;};ad_entity.correlate=function(containers){var view_handlers=ad_entity.viewHandlers;var view_handler;var correlation={};var handler_id='';var container;var container_id;for(container_id in containers){if(containers.hasOwnProperty(container_id)){container=containers[container_id];handler_id=container.data('data-ad-entity-view');if(view_handlers.hasOwnProperty(handler_id)){view_handler=view_handlers[handler_id];correlation[handler_id]=correlation[handler_id]||{handler:view_handler,containers:{}};correlation[handler_id].containers[container_id]=container;}}}
return correlation;};ad_entity.restrictAndInitialize=function(containers,context,settings){var view_handlers=ad_entity.viewHandlers;var helpers=ad_entity.helpers;var to_initialize=ad_entity.restrictAdsToScope(containers);var container;var container_id;var initialized;var disabled;var correlation;var handler_id;for(container_id in to_initialize){if(to_initialize.hasOwnProperty(container_id)){container=to_initialize[container_id];initialized=container.data('initialized');if(typeof initialized!=='boolean'){initialized=!helpers.hasClass(container.el,'not-initialized');container.data('initialized',initialized);}
if(initialized===true){delete to_initialize[container_id];}
else{disabled=helpers.hasClass(container.el,'initialization-disabled');container.data('disabled',disabled);if(disabled){delete to_initialize[container_id];}}}}
correlation=ad_entity.correlate(to_initialize);for(handler_id in view_handlers){if(view_handlers.hasOwnProperty(handler_id)){if(correlation.hasOwnProperty(handler_id)){correlation[handler_id].handler.initialize(correlation[handler_id].containers,context,settings);}}}};Drupal.behaviors.adEntityView={attach:function(context,settings){var containers=ad_entity.collectAdContainers(context,settings);var isEmptyObject=ad_entity.helpers.isEmptyObject;if(isEmptyObject(containers)){return;}
if(!(isEmptyObject(ad_entity.context))){ad_entity.context.addFrom(context);ad_entity.context.applyOn(containers);}
ad_entity.restrictAndInitialize(containers,context,settings);if(ad_entity.hasOwnProperty('settings')&&ad_entity.settings.hasOwnProperty('responsive')){if(ad_entity.settings.responsive===true){window.addEventListener('themeBreakpoint:changed',function(){ad_entity.restrictAndInitialize(containers,context,settings);});}}},detach:function(context,settings){var containers={};var collected=ad_entity.adContainers;var correlation;var handler_id;var container_items=context.querySelectorAll('.ad-entity-container');var length=container_items.length;var i;var el;for(i=0;i<length;i++){el=container_items[i];if(typeof el.id!=='string'||!(el.id.length>0)){continue;}
if(!collected.hasOwnProperty(el.id)){continue;}
containers[el.id]=collected[el.id];delete collected[el.id];}
correlation=ad_entity.correlate(containers);for(handler_id in ad_entity.viewHandlers){if(ad_entity.viewHandlers.hasOwnProperty(handler_id)){if(correlation.hasOwnProperty(handler_id)){correlation[handler_id].handler.detach(correlation[handler_id].containers,context,settings);}}}}};}(window.adEntity,Drupal,window));;(function(ad_entity,drupalSettings,window){ad_entity.viewHandlers=ad_entity.viewHandlers||{};ad_entity.viewHandlers.dfp_default={initialize:function(containers,context,settings){window.googletag.cmd.push(function(){var ad_tags=[];var onPageLoad='true';var container;var container_id;var ad_tag;var ad_el;if(this.numberOfAds>0){onPageLoad='false';}
for(container_id in containers){if(containers.hasOwnProperty(container_id)){container=containers[container_id];if(typeof container.ad_tag==='object'){continue;}
ad_el=container.el.querySelector('.google-dfp-ad');if(ad_el===null){continue;}
this.numberOfAds++;ad_tag={el:ad_el,data:function(key,value){return ad_entity.helpers.metadata(this.el,this,key,value);}};container.ad_tag=ad_tag;this.define(ad_tag,this.numberOfAds.toString(),onPageLoad,container);this.addEventsFor(container);ad_tags.push(ad_tag);}}
this.display(ad_tags);}.bind(this));},detach:function(containers,context,settings){},define:function(ad_tag,slotNumber,onPageLoad,container){var ad_id=ad_tag.el.id;var network_id=ad_tag.data('data-dfp-network');var unit_id=ad_tag.data('data-dfp-unit');var out_of_page=ad_tag.data('data-dfp-out-of-page');var slot;var sizes;var targeting;var key;var event_detail;if(out_of_page===true){slot=window.googletag.defineOutOfPageSlot('/'+network_id+'/'+unit_id,ad_id);}
else{sizes=ad_tag.data('data-dfp-sizes');if(typeof sizes!=='object'){sizes=[];}
slot=window.googletag.defineSlot('/'+network_id+'/'+unit_id,sizes,ad_id);}
ad_tag.data('slot',slot);targeting=container.data('data-ad-entity-targeting');if(typeof targeting!=='object'){targeting={};}
event_detail={slot:slot,targeting:targeting,slotNumber:slotNumber,onPageLoad:onPageLoad};ad_entity.helpers.trigger(window,'dfp:BeforeDisplay',false,true,event_detail);for(key in targeting){if(targeting.hasOwnProperty(key)){slot.setTargeting(key,targeting[key]);}}
if(this.withSlotOrder){slot.setTargeting('slotNumber',slotNumber);slot.setTargeting('onPageLoad',onPageLoad);}
slot.addService(window.googletag.pubads());},display:function(ad_tags){var slots=[[]];var slots_length;var slots_list;var slot;var i;var j;var k;var ad_tag;var unit_path;var exists;var slots_list_length;var ad_tags_length=ad_tags.length;for(i=0;i<ad_tags_length;i++){ad_tag=ad_tags[i];slot=ad_tag.data('slot');if(typeof slot==='object'){window.googletag.display(ad_tag.el.id);if(this.enableLazyLoad===false){unit_path=slot.getAdUnitPath();slots_length=slots.length;for(j=0;j<slots_length;j++){exists=false;slots_list=slots[j];slots_list_length=slots_list.length;for(k=0;k<slots_list_length;k++){if(drupalSettings.single_call_on_same_unit_path===false&&unit_path===slots_list[k].getAdUnitPath()){exists=true;break;}}
if(exists===false){slots_list.push(slot);break;}
if((j+1)===slots.length){slots.push([slot]);}}}}}
slots_length=slots.length;for(i=0;i<slots_length;i++){slots_list=slots[i];if(slots_list.length>0){if(typeof this.changeCorrelator==='boolean'){window.googletag.pubads().refresh(slots_list,{changeCorrelator:this.changeCorrelator});}
else{window.googletag.pubads().refresh(slots_list);}}}},addEventsFor:function(container){var initHandler=function(event){var helpers=ad_entity.helpers;var el=container.el;if(event.slot.getSlotElementId()===container.ad_tag.el.id){helpers.removeClass(el,'not-initialized');helpers.addClass(el,'initialized');container.data('initialized',true);if(event.isEmpty===true){helpers.addClass(el,'empty');helpers.removeClass(el,'not-empty');}
else{helpers.addClass(el,'not-empty');helpers.removeClass(el,'empty');}
helpers.trigger(el,'adEntity:initialized',true,true,{container:container});}};window.googletag.pubads().addEventListener('slotRenderEnded',initHandler,false);},numberOfAds:0,withSlotOrder:true,changeCorrelator:null,enableLazyLoad:false};if(drupalSettings.hasOwnProperty('dfp_enable_lazyload')){ad_entity.viewHandlers.dfp_default.enableLazyLoad=drupalSettings.dfp_enable_lazyload;}
if(drupalSettings.hasOwnProperty('dfp_order_info')){if(!drupalSettings.dfp_order_info){ad_entity.viewHandlers.dfp_default.withSlotOrder=false;}}
if(drupalSettings.hasOwnProperty('dfp_change_correlator')){ad_entity.viewHandlers.dfp_default.changeCorrelator=drupalSettings.dfp_change_correlator;}}(window.adEntity,drupalSettings,window));;