(function(drupalSettings,window){'use strict';window.themeBreakpoints={};if(typeof drupalSettings['theme_breakpoints']!=='undefined'){window.themeBreakpoints=new function(){this.Breakpoints=JSON.parse(drupalSettings['theme_breakpoints']);this.currentBreakpoint=false;this.getCurrentBreakpoint=function(){return this.currentBreakpoint;};var triggerBreakpointChange=function(){var breakpoint_changed_event=document.createEvent('CustomEvent');breakpoint_changed_event.initCustomEvent('themeBreakpoint:changed',true,true,this.currentBreakpoint);window.dispatchEvent(breakpoint_changed_event);}.bind(this);this.breakpointChangeHandler=function(){var mqls=this.mediaQueryListeners;var breakpointCandidate=false;for(var i=0;i<mqls.length;i++){if(mqls[i].matches){breakpointCandidate=this.Breakpoints[i];}}
if(breakpointCandidate&&breakpointCandidate!==this.currentBreakpoint){this.currentBreakpoint=breakpointCandidate;triggerBreakpointChange();}}.bind(this);this.mediaQueryListeners=function(){var breakpoints=this.Breakpoints;if(!Array.isArray(breakpoints)||breakpoints.length===0){return[];}
var currentBreakpoint=false;var mqls=[];for(var i=0;i<breakpoints.length;i++){if(breakpoints[i].mediaQuery===''){breakpoints[i].mediaQuery='(min-width: 0em)';}
var mql=window.matchMedia(breakpoints[i].mediaQuery);mql.addListener(this.breakpointChangeHandler);mqls.push(mql);if(mql.matches){currentBreakpoint=breakpoints[i];}}
this.currentBreakpoint=currentBreakpoint;return mqls;}.call(this);}();}})(drupalSettings,window);;(function(window,document){var settingsElement=document.getElementById('ad-entity-settings');if(!(typeof window.adEntity==='object')){window.adEntity={settings:{},helpers:{},queue:[]};}
else{window.adEntity.settings={};window.adEntity.helpers=window.adEntity.helpers||{};window.adEntity.queue=window.adEntity.queue||[];}
if(settingsElement!==null){window.adEntity.settings=JSON.parse(settingsElement.textContent);}
window.adEntity.usePersonalization=function(){var settings=window.adEntity.settings;if(!settings.hasOwnProperty('p13n')||(settings.p13n!==true)){return false;}
if(!settings.hasOwnProperty('consent')){return false;}
if(settings.consent.method==='disabled'){return true;}
if(settings.consent.method==='unbiased'){return null;}
return false;};}(window,window.document));;(function(window,drupalSettings){window.googletag=window.googletag||{};window.googletag.cmd=window.googletag.cmd||[];window.googletag.cmd.push(function(){var gpt=window.googletag;var p13n=false;if(window.adEntity&&typeof window.adEntity.usePersonalization==='function'){p13n=window.adEntity.usePersonalization();}
if(drupalSettings.dfp_enable_lazyload===true){var fetchMarginPercent=drupalSettings.dfp_fetch_margin_percent||0;var renderMarginPercent=drupalSettings.dfp_render_margin_percent||0;var mobileScaling=drupalSettings.dfp_mobile_scaling||0;if(fetchMarginPercent===0&&renderMarginPercent===0&&mobileScaling===0){gpt.pubads().enableLazyLoad();}else if(fetchMarginPercent===-1){gpt.pubads().enableLazyLoad({fetchMarginPrecent:-1});}else{gpt.pubads().enableLazyLoad({fetchMarginPercent:fetchMarginPercent,renderMarginPercent:renderMarginPercent,mobileScaling:mobileScaling});}}else{gpt.pubads().enableSingleRequest(true);gpt.pubads().collapseEmptyDivs();gpt.pubads().disableInitialLoad();}
if(p13n===true){gpt.pubads().setRequestNonPersonalizedAds(0);}
else if(p13n===false){gpt.pubads().setRequestNonPersonalizedAds(1);}
gpt.enableServices();});}(window,drupalSettings));;