/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, once) {
  var deprecatedMessageSuffix = "is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256";
  var originalJQOnce = $.fn.once;
  var originalJQRemoveOnce = $.fn.removeOnce;

  $.fn.once = function jQueryOnce(id) {
    Drupal.deprecationError({
      message: "jQuery.once() ".concat(deprecatedMessageSuffix)
    });
    return originalJQOnce.apply(this, [id]);
  };

  $.fn.removeOnce = function jQueryRemoveOnce(id) {
    Drupal.deprecationError({
      message: "jQuery.removeOnce() ".concat(deprecatedMessageSuffix)
    });
    return originalJQRemoveOnce.apply(this, [id]);
  };

  var drupalOnce = once;

  function augmentedOnce(id, selector, context) {
    originalJQOnce.apply($(selector, context), [id]);
    return drupalOnce(id, selector, context);
  }

  function remove(id, selector, context) {
    originalJQRemoveOnce.apply($(selector, context), [id]);
    return drupalOnce.remove(id, selector, context);
  }

  window.once = Object.assign(augmentedOnce, drupalOnce, {
    remove: remove
  });
})(jQuery, once);;
"use strict";

/**
 * @file
 * JS functionality for moving the modal component to the body when the modal is opened
 */
(function ($) {
  "use strict";

  $(document).on("show.bs.modal", function (event) {
    var $modalTarget = $(event.target);
    $modalTarget.once("modal-moved").each(function () {
      var $modal = $(this);
      $modal.detach();
      $("body").append($modal);
    });
  });
})(window.jQuery);;
"use strict";

/**
 * @file
 * Behaviors for the attsite_vbtheme theme.
 */
(function ($, _, Drupal) {
  'use strict';

  var init = false;
  /**
   * @type {string[]} Domains to be considered internal.
   *
   * No link tracking will be fired when navigating between these!
   */

  var linkInternalFilters = ['javascript:', 'experience.att.com', 'watch.att.com', 'more.att.com', 'audiencenetwork.att.com']; // Event.composedPath

  (function (e, d, w) {
    if (!e.composedPath) {
      e.composedPath = function () {
        if (this.path) {
          return this.path;
        }

        var target = this.target;
        this.path = [];

        while (target.parentNode !== null) {
          this.path.push(target);
          target = target.parentNode;
        }

        this.path.push(d, w);
        return this.path;
      };
    }
  })(Event.prototype, document, window);

  Drupal.behaviors.attsite_analytics = {
    attach: function attach(context) {
      if (init || drupalSettings.user.uid != null && drupalSettings.user.uid != 0) {
        return;
      }

      init = true;
      var counter = 10;

      var isAnalyticsLoaded = function isAnalyticsLoaded() {
        return window.s && window.s.isReadyToTrack();
      };

      var updateEventTracking = function updateEventTracking() {
        document.addEventListener('click', function (event) {
          var path = event.path || event.composedPath && event.composedPath();
          var eventPath = path.slice(0, path.length - 5);
          var targetLocation = 'link location';
          var destinationUrl;
          var linkName;

          for (var i = 0; i < eventPath.length; i++) {
            var currentTag = eventPath[i];

            if (currentTag.tagName === 'A' && !destinationUrl) {
              destinationUrl = currentTag.href || undefined;
              linkName = currentTag.textContent.trim();
            }

            if (destinationUrl && currentTag.getAttribute('data-track')) {
              targetLocation = "".concat(targetLocation, " | ").concat(currentTag.getAttribute('data-track'));
            }

            if (currentTag.classList && currentTag.classList.contains('content')) {
              break;
            }
          }

          destinationUrl && linkClicked(linkName, destinationUrl, targetLocation);
        }, true);
      };

      var linkClicked = function linkClicked(linkName, destinationUrl, targetLocation) {
        // These props were removed from s.setupLinkTrack()
        // call in the analytics script, in order to fill them here.
        window.s.prop19 = destinationUrl;
        window.s.prop20 = targetLocation; // Manually trigger "Other click" link tracking, as the analytics script
        // only triggers for "real" external links (not part of att.com)

        if (isExternalUrl(destinationUrl)) {
          s.tl(true, 'o', linkName, {
            prop19: destinationUrl,
            prop20: targetLocation
          });
        }
      };

      var isExternalUrl = function isExternalUrl(url) {
        url = url.toLowerCase().replace(/(^https?:\/\/)|(^\/\/)/, '');

        for (var i = 0; i < linkInternalFilters.length; ++i) {
          var filter = linkInternalFilters[i].toLowerCase();

          if (url.match(new RegExp('^[^\/\?]*' + escapeRegExp(filter), 'i'))) {
            return false;
          }
        }

        return true;
      };

      var escapeRegExp = function escapeRegExp(string) {
        return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      };

      (function initializeTracking() {
        if (!isAnalyticsLoaded()) {
          if (counter-- > 0) {
            setTimeout(initializeTracking, 256);
          } else {
            console.log('Adobe DTM is not running properly. Please check if the js is loaded and working!');
          }
        } else {
          updateEventTracking();
        }
      })();
    }
  };
})(window.jQuery, window._, window.Drupal);;
"use strict";

/**
 * @file
 * Behaviors for the attsite_vbtheme theme.
 */
(function ($, Drupal) {
  'use strict';

  Drupal.behaviors.attsite_vbtheme = {
    attach: function attach(context) {
      // Vartheme subtheme JavaScript behaviors goes here.
      var scroll = new SmoothScroll('a[href*="#"]', {
        header: '.sticky-header',
        easing: 'easeInQuad',
        speedAsDuration: true
      });
      $('.att-lightbox-button').click(function () {
        var dataTarget = $(this).attr('data-target') + ' img';
        showBlazy(dataTarget);
      });
    }
  }; // Function to swap blazy data-src and src attributes.

  var showBlazy = function showBlazy(dataTarget) {
    $(dataTarget).attr('src', $(dataTarget).attr('data-src')).addClass('b-loaded');
    $('<style>.media--loading:before {display: none}</style>').appendTo('head');
  };
})(window.jQuery, window.Drupal);;
/**
 * @file
 * Bootstrap Popovers.
 */

var Drupal = Drupal || {};

(function ($, Drupal, Bootstrap) {
  "use strict";

  var $document = $(document);

  /**
   * Extend the Bootstrap Popover plugin constructor class.
   */
  Bootstrap.extendPlugin('popover', function (settings) {
    return {
      DEFAULTS: {
        animation: !!settings.popover_animation,
        autoClose: !!settings.popover_auto_close,
        enabled: settings.popover_enabled,
        html: !!settings.popover_html,
        placement: settings.popover_placement,
        selector: settings.popover_selector,
        trigger: settings.popover_trigger,
        title: settings.popover_title,
        content: settings.popover_content,
        delay: parseInt(settings.popover_delay, 10),
        container: settings.popover_container
      }
    };
  });

  /**
   * Bootstrap Popovers.
   *
   * @todo This should really be properly delegated if selector option is set.
   */
  Drupal.behaviors.bootstrapPopovers = {
    $activePopover: null,
    attach: function (context) {
      // Immediately return if popovers are not available.
      if (!$.fn.popover || !$.fn.popover.Constructor.DEFAULTS.enabled) {
        return;
      }

      var _this = this;

      $document
        .on('show.bs.popover', '[data-toggle=popover]', function () {
          var $trigger = $(this);
          var popover = $trigger.data('bs.popover');

          // Only keep track of clicked triggers that we're manually handling.
          if (popover.options.originalTrigger === 'click') {
            if (_this.$activePopover && _this.getOption('autoClose') && !_this.$activePopover.is($trigger)) {
              _this.$activePopover.popover('hide');
            }
            _this.$activePopover = $trigger;
          }
        })
        // Unfortunately, :focusable is only made available when using jQuery
        // UI. While this would be the most semantic pseudo selector to use
        // here, jQuery UI may not always be loaded. Instead, just use :visible
        // here as this just needs some sort of selector here. This activates
        // delegate binding to elements in jQuery so it can work it's bubbling
        // focus magic since elements don't really propagate their focus events.
        // @see https://www.drupal.org/project/bootstrap/issues/3013236
        .on('focus.bs.popover', ':visible', function (e) {
          var $target = $(e.target);
          if (_this.$activePopover && _this.getOption('autoClose') && !_this.$activePopover.is($target) && !$target.closest('.popover.in')[0]) {
            _this.$activePopover.popover('hide');
            _this.$activePopover = null;
          }
        })
        .on('click.bs.popover', function (e) {
          var $target = $(e.target);
          if (_this.$activePopover && _this.getOption('autoClose') && !$target.is('[data-toggle=popover]') && !$target.closest('.popover.in')[0]) {
            _this.$activePopover.popover('hide');
            _this.$activePopover = null;
          }
        })
        .on('keyup.bs.popover', function (e) {
          if (_this.$activePopover && _this.getOption('autoClose') && e.which === 27) {
            _this.$activePopover.popover('hide');
            _this.$activePopover = null;
          }
        })
      ;

      var elements = $(context).find('[data-toggle=popover]').toArray();
      for (var i = 0; i < elements.length; i++) {
        var $element = $(elements[i]);
        var options = $.extend({}, $.fn.popover.Constructor.DEFAULTS, $element.data());

        // Store the original trigger.
        options.originalTrigger = options.trigger;

        // If the trigger is "click", then we'll handle it manually here.
        if (options.trigger === 'click') {
          options.trigger = 'manual';
        }

        // Retrieve content from a target element.
        var target = options.target || $element.is('a[href^="#"]') && $element.attr('href');
        var $target = $document.find(target).clone();
        if (!options.content && $target[0]) {
          $target.removeClass('visually-hidden hidden').removeAttr('aria-hidden');
          options.content = $target.wrap('<div/>').parent()[options.html ? 'html' : 'text']() || '';
        }

        // Initialize the popover.
        $element.popover(options);

        // Handle clicks manually.
        if (options.originalTrigger === 'click') {
          // To ensure the element is bound multiple times, remove any
          // previously set event handler before adding another one.
          $element
            .off('click.drupal.bootstrap.popover')
            .on('click.drupal.bootstrap.popover', function (e) {
              $(this).popover('toggle');
              e.preventDefault();
              e.stopPropagation();
            })
          ;
        }
      }
    },
    detach: function (context) {
      // Immediately return if popovers are not available.
      if (!$.fn.popover || !$.fn.popover.Constructor.DEFAULTS.enabled) {
        return;
      }

      // Destroy all popovers.
      $(context).find('[data-toggle="popover"]')
        .off('click.drupal.bootstrap.popover')
        .popover('destroy')
      ;
    },
    getOption: function(name, defaultValue, element) {
      var $element = element ? $(element) : this.$activePopover;
      var options = $.extend(true, {}, $.fn.popover.Constructor.DEFAULTS, ($element && $element.data('bs.popover') || {}).options);
      if (options[name] !== void 0) {
        return options[name];
      }
      return defaultValue !== void 0 ? defaultValue : void 0;
    }
  };

})(window.jQuery, window.Drupal, window.Drupal.bootstrap);
;
/**
 * @file
 * Bootstrap Tooltips.
 */

var Drupal = Drupal || {};

(function ($, Drupal, Bootstrap) {
  "use strict";

  /**
   * Extend the Bootstrap Tooltip plugin constructor class.
   */
  Bootstrap.extendPlugin('tooltip', function (settings) {
    return {
      DEFAULTS: {
        animation: !!settings.tooltip_animation,
        enabled: settings.tooltip_enabled,
        html: !!settings.tooltip_html,
        placement: settings.tooltip_placement,
        selector: settings.tooltip_selector,
        trigger: settings.tooltip_trigger,
        delay: parseInt(settings.tooltip_delay, 10),
        container: settings.tooltip_container
      }
    };
  });

  /**
   * Bootstrap Tooltips.
   *
   * @todo This should really be properly delegated if selector option is set.
   */
  Drupal.behaviors.bootstrapTooltips = {
    attach: function (context) {
      // Immediately return if tooltips are not available.
      if (!$.fn.tooltip || !$.fn.tooltip.Constructor.DEFAULTS.enabled) {
        return;
      }

      var elements = $(context).find('[data-toggle="tooltip"]').toArray();
      for (var i = 0; i < elements.length; i++) {
        var $element = $(elements[i]);
        var options = $.extend({}, $.fn.tooltip.Constructor.DEFAULTS, $element.data());
        $element.tooltip(options);
      }
    },
    detach: function (context) {
      // Immediately return if tooltips are not available.
      if (!$.fn.tooltip || !$.fn.tooltip.Constructor.DEFAULTS.enabled) {
        return;
      }

      // Destroy all tooltips.
      $(context).find('[data-toggle="tooltip"]').tooltip('destroy');
    }
  };

})(window.jQuery, window.Drupal, window.Drupal.bootstrap);
;
"use strict";

/**
 * @file
 * JS functionality for fixing line-heights smaller than font-sizes in the CKEDITOR.
 */
(function ($, Drupal) {
  Drupal.behaviors.attsite_line_height = {
    attach: function attach(context) {
      var lineHeightStr = "line-height";
      $(context).find('.field--type-text-long span').once("line-height").each(function () {
        var span = $(this);
        var spanStyle = span.attr("style");

        if (spanStyle) {
          if (spanStyle.indexOf(lineHeightStr) > -1 && span.css('display') !== 'block') {
            span.css('display', 'block');
          }
        }
      });
    }
  };
})(window.jQuery, window.Drupal);;
"use strict";

/**
 * @file
 * JS functionality for responsive tables inside CKeditor (Internet Explorer fix).
 */
(function ($, Drupal) {
  Drupal.behaviors.attsite_responsive_tables = {
    attach: function attach(context) {
      $(context).find('.paragraph--type--bp-simple table:not(table[responsivedisabled="true"])').once('ckeditor-table').each(function () {
        var table = $(this);
        var borderSettings = table.attr('border');

        if (borderSettings > 0) {
          table.addClass('has-border');
        } else {
          table.removeClass('has-border');
        }
      });
    }
  };
})(window.jQuery, window.Drupal);;
"use strict";

/**
 * @file
 * JS functionality for fixing new tab links.
 */
(function ($, Drupal) {
  Drupal.behaviors.attsite_new_tab_link = {
    attach: function attach(context) {
      $(context).find('.paragraph--type--bp-simple a[target="_blank"]').once("new-tab-link").on("click", function (e) {
        e.stopPropagation();
      });
    }
  };
})(window.jQuery, window.Drupal);;
/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

Drupal.debounce = function (func, wait, immediate) {
  var timeout;
  var result;
  return function () {
    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    var context = this;

    var later = function later() {
      timeout = null;

      if (!immediate) {
        result = func.apply(context, args);
      }
    };

    var callNow = immediate && !timeout;
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);

    if (callNow) {
      result = func.apply(context, args);
    }

    return result;
  };
};;
"use strict";

/**
 * @file
 * Simple file for declaring the attServices namespace.
 */
window.attServices = window.attServices ? window.attServices : {};;
"use strict";

/**
 * @file
 * Behaviors for the attsite_vbtheme theme.
 */
(function ($, Drupal, debounce, attServices) {
  'use strict';
  /**
   * Service to control teaser card components.
   */

  attServices.teaserCardController = new function () {
    /**
     * Method to init TC Card Components
     *
     * @param version
     *   TC Card version.
     */
    this.initTCCard = function (context) {
      var version = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : '';
      // @codingStandardsIgnoreLine
      var teaserCards = $(".paragraph--type--attsite-bp-teaser-card".concat(version), context);
      teaserCards.once('teaser-card').each(function () {
        var mobileTc = $('.tc-mobile .image', this);
        var mobileVideoContainer = mobileTc.find('.paragraph--type--attsite-brightcove-video');

        if (!mobileVideoContainer.length) {
          mobileVideoContainer = mobileTc.find('.paragraph--type--attsite-bp-youtube');
        }

        if (mobileVideoContainer.length) {
          var desktopTc = $('.tc-desktop .image', this);
          var desktopVideoContainer = desktopTc.find('.paragraph--type--attsite-brightcove-video');

          if (!desktopVideoContainer.length) {
            desktopVideoContainer = desktopTc.find('.paragraph--type--attsite-bp-youtube');
          }

          var mobileMove = debounce(function () {
            var ww = $(window).width();
            var type = ww <= 768 ? 'a' : 'b';

            if (desktopVideoContainer.data('type') !== type) {
              desktopVideoContainer.detach();
              mobileVideoContainer.remove();

              if (ww <= 768) {
                mobileTc.append(desktopVideoContainer);
              } else {
                desktopTc.append(desktopVideoContainer);
              }

              desktopVideoContainer.data('type', type);
            }
          }, 32);
          $(window).resize(mobileMove);
          mobileMove();
        }
      });
    };
  }();
})(window.jQuery, window.Drupal, window.Drupal.debounce, window.attServices);;
"use strict";

/**
 * @file
 * JS functionality for Teaser Card component.
 */
(function ($, Drupal, debounce, teaserCardController) {
  "use strict";

  Drupal.behaviors.attsite_vbtheme_component_teaser_card = {
    attach: function attach(context) {
      teaserCardController.initTCCard(context);
    }
  };
})(window.jQuery, window.Drupal, window.Drupal.debounce, window.attServices.teaserCardController);;
"use strict";

/**
 * @file
 * JS functionality for the Text Over Media Enhanced.
 */
(function ($, Drupal, drupalSettings) {
  "use strict";

  Drupal.behaviors.attsite_vbtheme_component_text_over_media_enh = {
    attach: function attach(context) {
      $.each(drupalSettings.att.textOverMediaEnh, function (paragraphId, mediaSettings) {
        // Adding the dynamic transition.
        $(mediaSettings.id).find(".media-overlay, .field--name-field-text").css({
          // @codingStandardsIgnoreLine
          transition: "all ".concat(mediaSettings.animationSpeed, "ms ease-in-out 0s")
        });
        var mediaOverlay = $(mediaSettings.id).find(".media-overlay");
        var overlayImage = $(mediaSettings.id).find(".field--name-field-tom-overlay-image");

        var checkMobileState = function checkMobileState() {
          var ww = $(window).width();

          var mouseEvents = function mouseEvents() {
            $(mediaSettings.id).on("mouseenter", function () {
              $(this).find(mediaOverlay).css({
                opacity: mediaSettings.hoverOpacity
              });
            }).on("mouseleave", function () {
              $(this).find(mediaOverlay).css({
                opacity: mediaSettings.opacity
              });
            });
          };

          if ($(mediaSettings.id).hasClass("mobile-hover") && ww <= 768) {
            mediaOverlay.css({
              opacity: mediaSettings.hoverOpacity
            });
            $(mediaSettings.id).off();

            if ($(mediaSettings.id).hasClass("animation-present")) {
              $(mediaSettings.id).removeClass("tom-animated");
            }

            if ($(mediaSettings.id).hasClass("hidden-text-present")) {
              $(mediaSettings.id).removeClass("hidden-text");
            }
          } else if ($(mediaSettings.id).hasClass("mobile-initial") && ww <= 768) {
            $(mediaSettings.id).off();
            mediaOverlay.css({
              opacity: mediaSettings.opacity
            });

            if ($(mediaSettings.id).hasClass("animation-present")) {
              $(mediaSettings.id).removeClass("tom-animated");
            }

            if ($(mediaSettings.id).hasClass("hidden-text-present")) {
              $(mediaSettings.id).find(".field--name-field-text").css({
                opacity: "0"
              });
            }
          } else {
            mediaOverlay.css({
              opacity: mediaSettings.opacity
            });
            mouseEvents();

            if ($(mediaSettings.id).hasClass("animation-present")) {
              $(mediaSettings.id).addClass("tom-animated");
            }

            if ($(mediaSettings.id).hasClass("hidden-text-present")) {
              $(mediaSettings.id).addClass("hidden-text");
              $(mediaSettings.id).find(".field--name-field-text").css({
                opacity: ""
              });
            }
          }
        };

        $(window).on("resize", checkMobileState);
        $(document).ready(checkMobileState);

        if (overlayImage.length > 0) {
          overlayImage.detach();
          mediaOverlay.append(overlayImage);
        }
      });
    }
  };
})(window.jQuery, window.Drupal, window.drupalSettings);;
/**
 * @file
 * Initializes all modifications.
 */

(function ($, Drupal) {

  'use strict';

  Drupal.behaviors.modifiers = {

    attach: function attach(context, settings) {
      // Process only if there are some modifiers.
      if (typeof settings.modifiers !== 'undefined') {
        this.initAttributes(context, settings);
        this.initSettings(context, settings);
      }
    },

    initSettings: function (context, settings) {
      // Skip processing if there are no modifications.
      if (typeof settings.modifiers.settings !== 'undefined') {
        var modifications = [];

        // Group all modifications into single array.
        $.each(settings.modifiers.settings, function (index, group) {
          modifications = modifications.concat(group);
        });

        // Process all modifications.
        $.each(modifications, function (index, modification) {
          var callback = window[modification.namespace][modification.callback];
          if (typeof callback === 'function') {
            // Check number of callback arguments.
            if (callback.length > 3) {
              // Callback with context and selector for backward compatibility.
              callback(context, modification.selector, modification.media, modification.args);
            }
            else {
              // Limit elements by context.
              $(modification.selector).each(function () {
                if ($.contains(context, this)) {
                  callback(this, modification.media, modification.args);
                }
              });
            }
          }
        });
      }
    },

    initAttributes: function (context, settings) {
      // Skip processing if there are no attributes.
      if (typeof settings.modifiers.attributes !== 'undefined') {
        var attributes = {};

        // Group all attributes into single array.
        $.each(settings.modifiers.attributes, function (index, group) {
          $.each(group, function (media, selectors) {
            // Initialize array for this media.
            if (typeof attributes[media] === 'undefined') {
              attributes[media] = {};
            }
            $.each(selectors, function (selector, values) {
              attributes[media][selector] = values;
            });
          });
        });

        // Process all attributes immediately.
        this.toggleAttributes(context, attributes);

        var that = this;
        // Process all attributes again after resize.
        window.addEventListener('resize', function () {
          that.toggleAttributes(context, attributes);
        });
      }
    },

    toggleAttributes: function (context, attributes) {
      var enable = {};
      var disable = {};

      // Check all media queries validity and split selectors to sets.
      $.each(attributes, function (media, selectors) {
        if (window.matchMedia(media).matches) {
          // Fill these selectors for enabling.
          $.each(selectors, function (selector, values) {
            enable[selector] = values;
          });
        }
        else {
          // Fill these selectors for disabling.
          $.each(selectors, function (selector, values) {
            disable[selector] = values;
          });
        }
      });

      // Remove unwanted attributes from target objects.
      $.each(disable, function (selector, values) {
        // Limit elements by context.
        var elements = $(selector).filter(function () {
          return $.contains(context, this);
        });
        if (elements.length) {
          // Process all attributes.
          $.each(values, function (attribute, value) {
            if (attribute === 'class') {
              $.each(value, function (index, item) {
                elements.removeClass(item);
              });
            }
            else {
              elements.prop(attribute, null);
            }
          });
        }
      });

      // Set required attributes to target objects.
      $.each(enable, function (selector, values) {
        // Limit elements by context.
        var elements = $(selector).filter(function () {
          return $.contains(context, this);
        });
        if (elements.length) {
          // Process all attributes.
          $.each(values, function (attribute, value) {
            if (attribute === 'class') {
              $.each(value, function (index, item) {
                elements.addClass(item);
              });
            }
            else if (typeof value === 'object') {
              elements.prop(attribute, value.join(' '));
            }
            else {
              elements.prop(attribute, value);
            }
          });
        }
      });
    }
  };

})(jQuery, Drupal);
;
